import {SaVaultPanel} from '../components/SaVaultPanel'
import {SaCollectionManager} from '../components/SaLibraryDialog'
import {SaWorkspaceSettings} from '../components/SaWorkspaceSettings'
import {loadSaPreferences,persistSaPreferences,type SaPreferences} from '../lib/saPreferences'
import {SaSplitDivider} from '../components/SaSplitDivider'
import {createPortal} from 'react-dom'
import {ArrowDownToLine,Play,ChevronsUp,ChevronsDown,Settings2,Settings,LockKeyhole} from 'lucide-react'
import {SaEnvironmentPicker} from '../components/SaEnvironmentPicker'
import {SaImportPanel} from '../components/SaImportPanel'
import {SaRunner} from '../components/SaRunner'
import {SaAssertions} from '../components/SaAssertions'
import {SaResponseViewer} from '../components/SaResponseViewer'
import {SaVariablesEditor} from '../components/SaVariablesEditor'
import {scopedEndpoint,type SaEnvironment} from '../../shared/saWorkspace'
import {redactSaEndpoint} from '../../shared/saPostman'
import { useState, useEffect, useCallback, useRef, type CSSProperties } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, ErrorNote, Field, Input, PageHeader, Select, Textarea } from '../components/ui'
import { CopyButton } from '../components/CopyButton'
import { SaVariableCues } from '../components/SaVariableCues'
import {SaUrlField} from '../components/SaUrlField'
import { SaDocsEditor } from '../components/SaDocsEditor'
import {SaSection} from '../components/SaSection'
import {SaCollectionTree} from '../components/SaCollectionTree'
import {SaChatPanel, type SaChatTurn} from '../components/SaChatPanel'
import { saPostmanApi } from '../lib/api'
import { endpointFromRequest, parseCurl, type SaEndpoint, type SaField, type SaSaved, type SaResponse, type SaCheck } from '../../shared/saPostman'

const tabs=['Docs','Params','Authorization','Headers','Body','Scripts','Settings','Variables'] as const
function Rows({rows,onChange,disabled}:{rows:SaField[];onChange:(rows:SaField[])=>void;disabled:boolean}){
  return <div className="space-y-2">{rows.map((r,i)=><div key={i} className="flex gap-2">
    <input type="checkbox" aria-label={`Enable row ${i+1}`} disabled={disabled} checked={r.enabled!==false} onChange={ev=>onChange(rows.map((v,j)=>j===i?{...v,enabled:ev.target.checked}:v))}/>
    {(['name','value','description'] as const).map(k=><Input key={k} aria-label={`${k} ${i+1}`} disabled={disabled} placeholder={k} value={r[k]??''} onChange={ev=>onChange(rows.map((v,j)=>j===i?{...v,[k]:ev.target.value}:v))}/>)}
    <Button variant="ghost" disabled={disabled} onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>Delete</Button>
  </div>)}<Button variant="outline" disabled={disabled} onClick={()=>onChange([...rows,{name:'',value:'',description:'',enabled:true}])}>Add row</Button></div>
}
type Incoming={curl?:string;title?:string;returnTo?:string;row?:SaSaved}
type TabMeta={name:string;dirty:boolean;busy:boolean;requestId?:string;chatSize?:'collapsed'|'normal'|'wide'}
export function SaPostmanPage(){const location=useLocation();return <TabbedWorkspace key={location.key} incoming={location.state as Incoming|null}/>}
function TabbedWorkspace({incoming}:{incoming:Incoming|null}){
 const [panes,setPanes]=useState([{id:crypto.randomUUID(),incoming}]),[active,setActive]=useState(''),[meta,setMeta]=useState<Record<string,TabMeta>>({}),[envId,setEnvId]=useState('')
 const environments=useQuery({queryKey:['sa-environments'],queryFn:saPostmanApi.environments})
 const [layoutSettings,setLayoutSettings]=useState(false),[vaultOpen,setVaultOpen]=useState(false)
 const [view,setView]=useState(loadSaPreferences)
 const [chatEpoch,setChatEpoch]=useState(0)
 const updateView=(next:Partial<SaPreferences>)=>{if(Object.hasOwn(next,'chatDefault'))setChatEpoch(v=>v+1);setView(previous=>{const value={...previous,...next};persistSaPreferences(value);return value})}
 const [chatHost,setChatHost]=useState<HTMLDivElement|null>(null)
 const currentId=active||panes[0]?.id
 const chatSize=meta[currentId]?.chatSize??view.chatDefault
 const onMeta=useCallback((id:string,next:TabMeta)=>setMeta(prev=>JSON.stringify(prev[id])===JSON.stringify(next)?prev:{...prev,[id]:next}),[])
 const newTab=()=>{const pane={id:crypto.randomUUID(),incoming:null};setPanes(prev=>[...prev,pane]);setActive(pane.id)}
 const openSaved=(row:SaSaved)=>{const existing=panes.find(p=>meta[p.id]?.requestId===row.id||p.incoming?.row?.id===row.id);if(existing){setActive(existing.id);return}const pane={id:crypto.randomUUID(),incoming:{row}};setPanes(prev=>[...prev,pane]);setActive(pane.id)}
 return <div data-sa-density={view.density} className={`grid gap-4 pr-5 ${chatSize==='normal'?'lg:grid-cols-[minmax(0,1fr)_360px]':chatSize==='wide'?'lg:grid-cols-[minmax(0,1fr)_520px]':'lg:grid-cols-[minmax(0,1fr)_48px]'}`}><div className="min-w-0"><div className="space-y-3 px-5 pt-5"><PageHeader kicker="API workspace" title="SAPostman" actions={<><Button variant="outline" onClick={newTab}>New request</Button><Button variant="outline" icon={<LockKeyhole className="size-4"/>} onClick={()=>setVaultOpen(true)}>Vault</Button><Button aria-label="Workspace settings" title="Workspace settings" aria-expanded={layoutSettings} variant={layoutSettings?'primary':'outline'} icon={<Settings className="size-4"/>} onClick={()=>setLayoutSettings(!layoutSettings)}/></>}/>{vaultOpen&&<SaVaultPanel onClose={()=>setVaultOpen(false)}/>} {layoutSettings&&<SaWorkspaceSettings value={view} onChange={updateView} onClose={()=>setLayoutSettings(false)}/>}<SaEnvironmentPicker active={envId} onActive={setEnvId}/><div role="tablist" aria-label="Open API requests" className="flex flex-wrap gap-1 border-b border-line pb-2">{panes.map(p=><div key={p.id} className={`flex items-center rounded border ${currentId===p.id?'border-forest bg-forest-soft':'border-line bg-panel'}`}><button role="tab" aria-selected={currentId===p.id} className="max-w-56 truncate px-3 py-2 text-sm" onClick={()=>setActive(p.id)}>{meta[p.id]?.name||p.incoming?.title||p.incoming?.row?.name||'New request'}{meta[p.id]?.dirty?' •':''}</button><button className="px-2 text-muted" aria-label={`Close request tab ${meta[p.id]?.name||'New request'}`} disabled={meta[p.id]?.busy} onClick={()=>{if(meta[p.id]?.dirty&&!confirm('Discard unsaved changes in this tab?'))return;if(panes.length===1){const next={id:crypto.randomUUID(),incoming:null};setPanes([next]);setActive(next.id)}else{setPanes(prev=>prev.filter(t=>t.id!==p.id));if(currentId===p.id)setActive(panes.find(t=>t.id!==p.id)!.id)}}}>×</button></div>)}<Button variant="ghost" onClick={newTab}>+ New tab</Button></div></div>{panes.map(p=><div key={p.id} hidden={p.id!==currentId}><Workspace id={p.id} incoming={p.incoming} environment={environments.data?.find(e=>e.id===envId)} onMeta={onMeta} onOpenSaved={openSaved} chatHost={chatHost} active={p.id===currentId} preferences={view} chatEpoch={chatEpoch} onEditorWidth={width=>updateView({width})}/></div>)}</div><div ref={setChatHost} className="min-w-0 pt-5"/></div>
}
function Workspace({id,incoming,environment,onMeta,onOpenSaved,chatHost,active,preferences,chatEpoch,onEditorWidth}:{id:string;incoming:Incoming|null;environment?:SaEnvironment;onMeta:(id:string,meta:TabMeta)=>void;onOpenSaved:(row:SaSaved)=>void;chatHost:HTMLDivElement|null;active:boolean;preferences:SaPreferences;chatEpoch:number;onEditorWidth:(width:number)=>void}){
  const {layout,width:editorWidth}=preferences
  const draft=(request?:Parameters<typeof endpointFromRequest>[0])=>({...endpointFromRequest(request),settings:{timeoutMs:preferences.timeoutMs}})
  const qc=useQueryClient()
  const vault=useQuery({queryKey:['sa-vault'],queryFn:saPostmanApi.vault,enabled:active})
  const [executionId,setExecutionId]=useState<string|null>(null),[cancelling,setCancelling]=useState(false)
  const executionRef=useRef<string|null>(null)
  useEffect(()=>()=>{if(executionRef.current)void saPostmanApi.cancelExecution(executionRef.current).catch(()=>{})},[])
  const [collapsed,setCollapsed]=useState({library:false,request:false,versions:true,response:false})
  const [importExpanded,setImportExpanded]=useState(false)
  const toggle=(key:keyof typeof collapsed)=>setCollapsed(prev=>({...prev,[key]:!prev[key]}))
  const saved=useQuery({queryKey:['sa-endpoints'],queryFn:saPostmanApi.list})
  const history=useQuery({queryKey:['sa-history'],queryFn:saPostmanApi.history})
  const collections=useQuery({queryKey:['sa-collections'],queryFn:saPostmanApi.collections})
  const [collection,setCollection]=useState('all'),[chatOverride,setChatOverride]=useState<{size:'collapsed'|'normal'|'wide';epoch:number}|null>(null)
  const chatSize=chatOverride?.epoch===chatEpoch?chatOverride.size:preferences.chatDefault
  const setChatSize=(size:'collapsed'|'normal'|'wide')=>setChatOverride({size,epoch:chatEpoch})
  const [e,setE]=useState<SaEndpoint>(()=>{try{if(incoming?.row)return structuredClone(incoming.row.config);return {...draft(parseCurl(incoming?.curl??'')),name:incoming?.title??''}}catch{return draft()}})
  const [selection,setSelection]=useState<SaSaved|null>(incoming?.row??null)
  const versions=useQuery({queryKey:['sa-versions',selection?.id],queryFn:()=>saPostmanApi.versions(selection!.id),enabled:!!selection})
  const [tab,setTab]=useState<typeof tabs[number]>('Body'),[left,setLeft]=useState('saved'),[curl,setCurl]=useState(incoming?.curl??'')
  const [error,setError]=useState<Error|null>(()=>{if(!incoming?.curl)return null;try{parseCurl(incoming.curl);return null}catch(err){return err as Error}})
  const [busy,setBusy]=useState(false),[response,setResponse]=useState<SaResponse|null>(null),[checks,setChecks]=useState<SaCheck[]>([])
  const [chatKey,setChatKey]=useState(0)
  const [prompt,setPrompt]=useState(''),[ai,setAi]=useState<{explanation:string;curl:string;docs:string}|null>(null),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false)
  const [previous,setPrevious]=useState<SaResponse|null>(null),[requestPreview,setRequestPreview]=useState<Awaited<ReturnType<typeof saPostmanApi.preview>>|null>(null)
  const activeCollection=collections.data?.find(c=>c.id===e.collectionId)
  const [tool,setTool]=useState<'import'|'runner'|null>(null),[manageCollections,setManageCollections]=useState(false)
  const [previewSignature,setPreviewSignature]=useState('')
  const [collectionDraft,setCollectionDraft]=useState<NonNullable<SaEndpoint['variables']>|null>(null)
  useEffect(()=>onMeta(id,{name:e.name,dirty,busy,requestId:selection?.id,chatSize}),[id,e.name,dirty,busy,selection?.id,chatSize,onMeta])
  useEffect(()=>{
    if(!selection||!e.collectionId||!collections.data||collections.data.some(c=>c.id===e.collectionId))return
    const moved=saved.data?.find(row=>row.id===selection.id)
    if(!moved||moved.version<=selection.version||moved.config.collectionId)return
    setSelection(moved)
    setE(current=>dirty?{...current,collectionId:null,variables:scopedEndpoint(current,moved.config.variables).variables}:structuredClone(moved.config))
    setCollectionDraft(null)
    setRequestPreview(null)
  },[collections.data,saved.data,selection,e.collectionId,dirty])
  const effective=()=>scopedEndpoint(e,activeCollection?.variables,environment?.variables)
  let cueEndpoint=e;try{cueEndpoint=effective();cueEndpoint={...cueEndpoint,variables:[...(cueEndpoint.variables??[]).filter(v=>!v.name.startsWith('vault.')),...(vault.data?.unlocked?vault.data.entries.map(v=>({name:`vault.${v.name}`,value:'[Vault secret]',secret:true,enabled:true})):[])]}}catch{/* Send/preview reports invalid scope */}
  const patch=(p:Partial<SaEndpoint>)=>{setRequestPreview(null);if(Object.hasOwn(p,'collectionId'))setCollectionDraft(null);setE(prev=>({...prev,...p}));setDirty(true)}
  const replace=(next:SaEndpoint,sel:SaSaved|null=null)=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;setCollectionDraft(null);setChatKey(k=>k+1);setPrompt('');setE(structuredClone(next));setSelection(sel);setDirty(false);setPrevious(null);setRequestPreview(null);setResponse(null);setChecks([]);setError(null);setAi(null)}
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn()}catch(err){setError(err instanceof Error?err:new Error(String(err)))}finally{setBusy(false)}}
  const refresh=()=>{void qc.invalidateQueries({queryKey:['sa-endpoints']});void qc.invalidateQueries({queryKey:['sa-history']});void qc.invalidateQueries({queryKey:['sa-versions']});void qc.invalidateQueries({queryKey:['sa-collections']});void qc.invalidateQueries({queryKey:['trash']});void qc.invalidateQueries({queryKey:['sa-vault']})}
  const hit=()=>action(async()=>{const id=crypto.randomUUID();executionRef.current=id;setExecutionId(id);setCancelling(false);setPrevious(response??previous);setResponse(null);setChecks([]);try{const r=await saPostmanApi.execute(effective(),id);setResponse(r.response);setChecks(r.checks);if(r.error||r.historyError)setError(new Error(r.error??r.historyError));refresh()}finally{executionRef.current=null;setExecutionId(null);setCancelling(false)}})
  const cancel=async()=>{if(!executionId)return;setCancelling(true);try{await saPostmanApi.cancelExecution(executionId)}catch(err){setError(err as Error);setCancelling(false)}}
  const save=(copy=false)=>action(async()=>{const row=selection&&!copy?await saPostmanApi.update(selection.id,selection.version,e):await saPostmanApi.create(e);setSelection(row);setE(row.config);setDirty(false);refresh()})
  const saveVariables=async(variables:NonNullable<SaEndpoint['variables']>)=>{
    if(variables.some(v=>v.name.startsWith('vault.')&&v.value!=='[Vault secret]'))throw new Error('Edit vault secrets using the Vault button')
    variables=variables.filter(v=>!v.name.startsWith('vault.'))
    const changed=variables.filter(v=>JSON.stringify(v)!==JSON.stringify(cueEndpoint.variables?.find(old=>old.name===v.name)))
    const ownNames=new Set((e.variables??[]).map(v=>v.name))
    const envChanges=changed.filter(v=>!ownNames.has(v.name)&&environment?.variables.some(old=>old.name===v.name))
    const collectionChanges=changed.filter(v=>!ownNames.has(v.name)&&!envChanges.includes(v)&&activeCollection?.variables?.some(old=>old.name===v.name))
    if(envChanges.length||collectionChanges.length){setBusy(true);setError(null);try{if(environment&&envChanges.length)await saPostmanApi.updateEnvironment({...environment,variables:environment.variables.map(v=>envChanges.find(n=>n.name===v.name)??v)});if(activeCollection&&collectionChanges.length)await saPostmanApi.updateCollection({...activeCollection,variables:(activeCollection.variables??[]).map(v=>collectionChanges.find(n=>n.name===v.name)??v)});await qc.invalidateQueries({queryKey:['sa-environments']});refresh();return}catch(err){setError(err as Error);throw err}finally{setBusy(false)}}
    const next={...e,variables:[...(e.variables??[]).filter(v=>!changed.some(n=>n.name===v.name)),...changed]}
    if(!next.name.trim()){setError(new Error('Enter an endpoint name before saving a variable'));throw new Error('Endpoint name required')}
    setBusy(true);setError(null)
    try{const row=selection?await saPostmanApi.update(selection.id,selection.version,next):await saPostmanApi.create(next);setE(row.config);setSelection(row);setDirty(false);refresh()}catch(err){setError(err as Error);throw err}finally{setBusy(false)}
  }
  const moveRequest=(row:SaSaved,collectionId:string|null)=>action(async()=>{if(selection?.id===row.id&&dirty)throw new Error('Save current edits before moving this API');const updated=await saPostmanApi.update(row.id,row.version,{...row.config,collectionId});if(selection?.id===row.id){setSelection(updated);setE(updated.config);setDirty(false)}refresh()})
  const ask=(mode:'generate'|'trace'|'docs'|'ask',history:SaChatTurn[]=[])=>{const lastError=error?.message??'';return action(async()=>setAi(await saPostmanApi.assist({mode,history:history.map(turn=>({...turn,content:turn.content.slice(0,8000)})),prompt:prompt.trim()||({generate:'Generate a request based on these endpoint docs.',trace:'Diagnose the response or network error.',docs:'Document this endpoint.',ask:'Review this endpoint and suggest what I should check next.'})[mode],endpoint:effective(),response:response?JSON.stringify({status:response.status,statusText:response.statusText,headers:Object.fromEntries(Object.entries(response.headers).filter(([key])=>!/cookie|authorization|token|key/i.test(key))),body:response.body}).slice(0,50000):'',error:lastError})))}
  const download=(name:string,data:unknown)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const requestCommand=(row:SaSaved,command:string,value?:string)=>action(async()=>{
    if(command==='export'){download(`${row.name.replace(/[^a-z0-9_-]/gi,'_')}.sapostman.json`,{format:'sapostman-collection',version:1,name:row.name,variables:[],endpoints:[redactSaEndpoint(row.config)]});return}
    if(command==='duplicate'){const copy=await saPostmanApi.create({...row.config,name:row.name+' copy'});refresh();onOpenSaved(copy);return}
    if(selection?.id===row.id&&dirty)throw new Error('Save current edits before modifying this API')
    if(command==='delete'){if(!confirm(`Move ${row.name} to Trash? You can restore it for 30 days.`))return;await saPostmanApi.remove(row.id);if(selection?.id===row.id){setSelection(null);setDirty(true)}}else{const config=command==='rename'?{...row.config,name:value??row.name}:{...row.config,collectionId:value||null};const updated=await saPostmanApi.update(row.id,row.version,config);if(selection?.id===row.id){setSelection(updated);setE(updated.config)}}refresh()
  })
  return <><div className="min-w-0 space-y-4 p-5">
    {incoming?.returnTo?.startsWith('/projects/')&&<Link className="text-sm underline" to={incoming.returnTo}>Back to POC</Link>}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line bg-panel p-2">
      <div className="flex flex-wrap items-center gap-1"><Button variant={tool==='import'?'primary':'ghost'} icon={<ArrowDownToLine className="size-4"/>} onClick={()=>setTool(tool==='import'?null:'import')}>Import APIs</Button><Button variant={tool==='runner'?'primary':'ghost'} icon={<Play className="size-4"/>} onClick={()=>setTool(tool==='runner'?null:'runner')}>Collection runner</Button></div>
      <div className="flex flex-wrap items-center gap-1"><Button variant="ghost" title="Collapse all panels" icon={<ChevronsUp className="size-4"/>} onClick={()=>{setCollapsed({library:true,request:true,versions:true,response:true});setTool(null);setImportExpanded(false);setChatSize('collapsed')}}>Collapse all</Button><Button variant="ghost" title="Expand all panels" icon={<ChevronsDown className="size-4"/>} onClick={()=>{setCollapsed({library:false,request:false,versions:false,response:false});setImportExpanded(true);setChatSize('normal')}}>Expand all</Button></div>
    </div>
    <div hidden={tool!=='import'}><SaImportPanel defaultOpen onImported={refresh}/></div>
    <div hidden={tool!=='runner'}><SaRunner defaultOpen collections={collections.data??[]} requests={saved.data??[]} environment={environment} onFinish={refresh}/></div>
    <ErrorNote error={error??saved.error??history.error??versions.error??collections.error}/>
    <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)]">
      <SaSection title="API library" collapsed={collapsed.library} onToggle={()=>toggle('library')}><div className="flex items-center justify-between gap-2"><div className="flex gap-1"><Button variant={left==='saved'?'primary':'ghost'} onClick={()=>setLeft('saved')}>Collections</Button><Button variant={left==='history'?'primary':'ghost'} onClick={()=>setLeft('history')}>History</Button></div><Button aria-label="Manage collections" title="Manage collections" variant="ghost" icon={<Settings2 className="size-4"/>} onClick={()=>{setLeft('saved');setManageCollections(!manageCollections)}}/></div>      <div className="max-h-[700px] space-y-2 overflow-auto">
        {left==='saved'?<SaCollectionTree collections={collections.data??[]} requests={saved.data??[]} selected={selection?.id} busy={busy} onSelect={onOpenSaved} onMove={moveRequest} onCommand={requestCommand} onTrash={async ids=>{if(!confirm(`Move ${ids.length} API${ids.length===1?'':'s'} to Trash? Restore is available for 30 days.`))return false;let moved=false;await action(async()=>{await saPostmanApi.trashRequests(ids);if(selection&&ids.includes(selection.id)){setSelection(null);setDirty(true)}moved=true;refresh()});return moved}} onCollectionMenu={c=>{setCollection(c.id);setManageCollections(true)}}/>:(history.data??[]).map(row=><div key={row.id} className="rounded border border-line p-2"><button disabled={busy} className="w-full text-left text-sm" onClick={()=>void action(async()=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;const item=await saPostmanApi.historyItem(row.id);setCollectionDraft(null);setChatKey(k=>k+1);setPrompt('');setAi(null);setE(item.request);setSelection(null);setDirty(false);setResponse(item.response);setChecks(item.checks);setError(item.error?new Error(item.error):null)})}><span className="block font-semibold">{row.name}</span><span className="text-xs text-muted">{row.error?'Failed':row.summary.status} · {new Date(row.created_at).toLocaleString()}</span></button><Button variant="ghost" disabled={busy} onClick={()=>void action(async()=>{await saPostmanApi.removeHistory(row.id);refresh()})}>Delete history</Button></div>)}
        {left==='saved'&&!saved.data?.length&&<p className="text-xs text-muted">Save an endpoint to reuse it.</p>}{left==='history'&&<p className="text-xs text-muted">Last 100 sends. Authentication is removed; re-enter credentials before replay.</p>}
      </div>{left==='saved'&&manageCollections&&<SaCollectionManager key={collection} collections={collections.data??[]} initialId={collection} busy={busy} error={error} onClose={()=>setManageCollections(false)} onCommand={(command,id,name)=>action(async()=>{
        if(command==='export'){const data=await saPostmanApi.exportCollection(id);download(`${data.name.replace(/[^a-z0-9_-]/gi,'_')}.sapostman.json`,data);return}
        if(command==='delete'){if(!confirm('Delete this collection? APIs move to Unfiled and keep their variables and history.'))return;await saPostmanApi.deleteCollection(id);setCollection('all')}
        if(command==='rename')await saPostmanApi.renameCollection(id,name!)
        if(command==='create')await saPostmanApi.createCollection(name!)
        setManageCollections(false);refresh()
      })}/>}</SaSection>
      <div className="min-w-0 @container"><div className={`grid items-start gap-4 ${layout==='horizontal'?'@min-[820px]:grid-cols-[var(--sa-split-columns)]':''}`} style={{'--sa-split-columns':`minmax(0,${editorWidth}fr) 8px minmax(0,${100-editorWidth}fr)`} as CSSProperties}><div className="sa-code-fields min-w-0 resize-y overflow-auto @container" style={{minHeight:200,'--sa-editor-font-size':`${preferences.fontSize}px`,'--sa-editor-white-space':preferences.wordWrap?'pre-wrap':'pre'} as CSSProperties}><SaSection title="Request" collapsed={collapsed.request} onToggle={()=>toggle('request')}>
        <div className="flex flex-wrap items-center gap-2"><Input aria-label="Endpoint name" className="min-w-40 flex-1" disabled={busy} value={e.name} placeholder="Endpoint name" onChange={ev=>patch({name:ev.target.value})}/><Button disabled={busy||!e.name.trim()} onClick={()=>void save()}>{selection?'Update':'Save'}</Button>{selection&&<><Button variant="outline" disabled={busy} onClick={()=>void save(true)}>Save as new</Button><Button variant="ghost" disabled={busy} onClick={()=>{if(confirm('Move this API to Trash? You can restore it with its versions for 30 days.'))void action(async()=>{await saPostmanApi.remove(selection.id);setSelection(null);setDirty(true);refresh()})}}>Delete endpoint</Button></>}{dirty&&<span className="text-xs text-muted">Unsaved</span>}</div>
        <Field label="Collection"><Select aria-label="Endpoint collection" disabled={busy} value={e.collectionId??''} onChange={ev=>patch({collectionId:ev.target.value||null})}><option value="">Unfiled</option>{collections.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><details open={importExpanded} onToggle={ev=>setImportExpanded(ev.currentTarget.open)}><summary className="cursor-pointer text-sm">Import cURL</summary><Textarea wrap={preferences.wordWrap?'soft':'off'} aria-label="Import cURL" rows={3} className="mt-2 font-mono text-xs" value={curl} onChange={ev=>setCurl(ev.target.value)}/><Button variant="outline" disabled={busy||!curl.trim()} onClick={()=>{try{replace({...draft(parseCurl(curl)),name:e.name})}catch(err){setError(err as Error)}}}>Import cURL</Button></details>
        <div className="grid grid-cols-[100px_minmax(0,1fr)] gap-2 @min-[480px]:grid-cols-[100px_minmax(0,1fr)_auto]"><Select aria-label="HTTP method" className="col-start-1 row-start-1 w-full" disabled={busy} value={e.method} onChange={ev=>patch({method:ev.target.value})}>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(m=><option key={m}>{m}</option>)}</Select><div className="col-span-2 col-start-1 row-start-2 min-w-0 @min-[480px]:col-span-1 @min-[480px]:col-start-2 @min-[480px]:row-start-1"><SaUrlField endpoint={cueEndpoint} busy={busy} onChange={url=>patch({url})} onSave={saveVariables}/></div><Button className="col-start-2 row-start-1 justify-self-end @min-[480px]:col-start-3" variant={executionId?'danger':'primary'} loading={executionId?cancelling:busy} disabled={executionId?cancelling:!e.url.trim()} onClick={()=>executionId?void cancel():void hit()}>{executionId?cancelling?'Cancelling...':'Cancel':'Hit / Send'}</Button></div>
        <Button variant="outline" disabled={busy||!e.url.trim()} onClick={()=>void action(async()=>{const endpoint=effective();setRequestPreview(await saPostmanApi.preview(endpoint));setPreviewSignature(JSON.stringify(cueEndpoint))})}>Preview final request</Button>
        {requestPreview&&previewSignature===JSON.stringify(cueEndpoint)&&<div className="space-y-2 rounded border border-line p-3"><div className="flex items-center justify-between"><strong className="text-sm">Final request · not sent</strong><Button variant="ghost" onClick={()=>setRequestPreview(null)}>Close preview</Button></div><p className="text-xs text-warn">Preview contains resolved values, including credentials. Review before copying.</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-all font-mono text-xs">{JSON.stringify(requestPreview,null,2)}</pre></div>}
        <div role="tablist" className="flex flex-wrap gap-1 border-b border-line pb-2">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={`rounded px-3 py-2 text-sm ${tab===t?'bg-forest text-paper':'text-muted'}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
        <SaVariableCues endpoint={cueEndpoint} busy={busy} onSave={saveVariables}/>
        {['GET','HEAD'].includes(e.method)&&<p className="text-xs text-muted">{e.method} sends URL and params only; body content is retained in the editor but is not sent.</p>}
        {tab==='Docs'&&<div className="space-y-3"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?'Edit docs':'Preview docs'}</Button><CopyButton text={e.docs} label="Copy docs"/><Button variant="outline" disabled={busy} onClick={()=>{setChatSize('normal');void ask('docs')}}>Generate docs with AI</Button></div>{preview?<SaDocsEditor key="preview" docs={e.docs} html={e.docsHtml} disabled onChange={()=>{}}/>:<SaDocsEditor docs={e.docs} html={e.docsHtml} disabled={busy} onChange={(docs,docsHtml)=>patch({docs,docsHtml})}/>}<p className="text-xs text-muted">Save / Update stores formatting with the endpoint version.</p></div>}
        {tab==='Params'&&<><p className="text-xs text-muted">Enabled rows are appended to existing URL query params.</p><Rows rows={e.params} disabled={busy} onChange={params=>patch({params})}/></>}
        {tab==='Headers'&&<Rows rows={e.headers} disabled={busy} onChange={headers=>patch({headers})}/>}
        {tab==='Variables'&&<div className="space-y-3"><p className="text-xs text-muted">Vault references use {'{{vault.name}}'} and are managed with the Vault button. Scope precedence: collection → environment ({environment?.name??'none'}) → API → runner response variables.</p>{activeCollection&&<div className="space-y-2 rounded border border-line p-3"><h3 className="font-semibold">Collection variables · {activeCollection.name}</h3><SaVariablesEditor rows={collectionDraft??activeCollection.variables??[]} disabled={busy} onChange={setCollectionDraft}/><Button disabled={busy||collectionDraft===null} onClick={()=>void action(async()=>{await saPostmanApi.updateCollection({...activeCollection,variables:collectionDraft??[]});setCollectionDraft(null);refresh()})}>Save collection variables</Button></div>}<p className="text-sm text-muted">Use {'{{base_url}}'}, {'{{token}}'} or {'{{customer_id}}'} in URL, params, headers, auth, body and script rules. Variables are saved per endpoint and version. Values are substituted as literal text.</p><Rows rows={e.variables??[]} disabled={busy} onChange={variables=>patch({variables})}/>{(e.variables??[]).map((v,i)=><label key={i} className="flex items-center gap-2 text-xs"><input type="checkbox" disabled={busy} checked={v.secret??false} onChange={ev=>patch({variables:(e.variables??[]).map((row,j)=>j===i?{...row,secret:ev.target.checked}:row)})}/>Treat {v.name||`variable ${i+1}`} as secret (remove from history and AI)</label>)}</div>}
        {tab==='Authorization'&&<div className="space-y-3"><Field label="Auth type"><Select disabled={busy} value={e.auth.type} onChange={ev=>patch({auth:{...e.auth,type:ev.target.value as SaEndpoint['auth']['type']}})}>{[['none','No Auth'],['basic','Basic Auth'],['bearer','Bearer Token'],['api-key','API Key'],['jwt','JWT Bearer'],['oauth2','OAuth 2.0 access token']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</Select></Field>
          {e.auth.type==='basic'&&(['username','password'] as const).map(k=><Field key={k} label={k}><Input disabled={busy} type={k==='password'?'password':'text'} value={e.auth[k]} onChange={ev=>patch({auth:{...e.auth,[k]:ev.target.value}})}/></Field>)}
          {['bearer','jwt','oauth2'].includes(e.auth.type)&&<Field label="Token"><Input type="password" disabled={busy} value={e.auth.token} onChange={ev=>patch({auth:{...e.auth,token:ev.target.value}})}/></Field>}
          {e.auth.type==='oauth2'&&<p className="text-xs text-muted">Paste an existing access token. Acquire/refresh tokens with your OAuth provider.</p>}
          {e.auth.type==='api-key'&&<>{(['key','value'] as const).map(k=><Field key={k} label={k}><Input disabled={busy} type={k==='value'?'password':'text'} value={e.auth[k]} onChange={ev=>patch({auth:{...e.auth,[k]:ev.target.value}})}/></Field>)}<Select aria-label="API key location" disabled={busy} value={e.auth.location} onChange={ev=>patch({auth:{...e.auth,location:ev.target.value as 'header'|'query'}})}><option value="header">Header</option><option value="query">Query params</option></Select></>}
          <p className="text-xs text-muted">Save stores auth locally and in backups. Send history and AI remove auth fields.</p>
        </div>}
        {tab==='Body'&&<div className="space-y-3"><div className="flex flex-wrap gap-3">{(['none','form-data','urlencoded','raw','binary','graphql'] as const).map(m=><label key={m} className="flex items-center gap-1 text-sm"><input type="radio" name={`body-mode-${id}`} disabled={busy} checked={e.bodyMode===m} onChange={()=>patch({bodyMode:m})}/>{m==='urlencoded'?'x-www-form-urlencoded':m==='graphql'?'GraphQL':m}</label>)}</div>
          {e.bodyMode==='raw'&&<div className="flex gap-2"><Select className="w-40" aria-label="Raw body format" disabled={busy} value={e.rawType} onChange={ev=>patch({rawType:ev.target.value as SaEndpoint['rawType']})}>{['JSON','Text','JavaScript','HTML','XML'].map(t=><option key={t}>{t}</option>)}</Select><Button variant="outline" disabled={busy} onClick={()=>{try{patch({body:JSON.stringify(JSON.parse(e.body),null,2)})}catch{setError(new Error('Beautify requires valid JSON'))}}}>Beautify JSON</Button></div>}
          {['raw','graphql'].includes(e.bodyMode)&&<Field label={e.bodyMode==='graphql'?'GraphQL query':'Request body'}><Textarea wrap={preferences.wordWrap?'soft':'off'} aria-label="Request body" disabled={busy} rows={8} className="font-mono text-xs" value={e.body} onChange={ev=>patch({body:ev.target.value})}/></Field>}
          {['form-data','urlencoded'].includes(e.bodyMode)&&<Rows rows={e.form} disabled={busy} onChange={form=>patch({form})}/>}
          {e.bodyMode==='binary'&&<Field label="Binary file (max 2 MB)"><input type="file" disabled={busy} onChange={ev=>{const file=ev.target.files?.[0];if(!file)return;void action(async()=>{if(file.size>2000000)throw new Error('File exceeds 2 MB');const bytes=new Uint8Array(await file.arrayBuffer());let str='';for(const b of bytes)str+=String.fromCharCode(b);patch({binaryName:file.name,binaryBase64:btoa(str)})})}}/><p className="text-xs text-muted">{e.binaryName||'No file selected'}</p></Field>}
          {e.bodyMode==='graphql'&&<Field label="GraphQL variables (JSON)"><Textarea wrap={preferences.wordWrap?'soft':'off'} className="font-mono text-xs" disabled={busy} value={e.graphqlVariables} onChange={ev=>patch({graphqlVariables:ev.target.value})}/></Field>}
        </div>}
        {tab==='Scripts'&&<div className="space-y-3"><SaAssertions script={e.scripts.post} disabled={busy} onChange={post=>patch({scripts:{...e.scripts,post}})}/><h3 className="font-semibold">Runner response variables</h3><p className="text-xs text-muted">Extract JSON paths such as access_token or data.id for the next request's {'{{token}}'} variable.</p><SaVariablesEditor showEnabled={false} valueLabel="Response JSON path" disabled={busy} rows={(e.extracts??[]).map(r=>({name:r.name,value:r.path,secret:r.secret??true}))} onChange={rows=>patch({extracts:rows.map(r=>({name:r.name,path:r.value,secret:r.secret}))})}/><p className="text-xs text-muted">JSON rules, not JavaScript. Pre-request adds headers/params. Post-response checks status, headers or JSON paths. Invalid rules stop sending.</p><Field label="Pre-request rules"><Textarea wrap={preferences.wordWrap?'soft':'off'} rows={5} className="font-mono text-xs" disabled={busy} value={e.scripts.pre} onChange={ev=>patch({scripts:{...e.scripts,pre:ev.target.value}})} placeholder={'{"headers":{"X-Test":"true"},"params":{"debug":"1"}}'}/></Field><Field label="Post-response assertions"><Textarea wrap={preferences.wordWrap?'soft':'off'} rows={6} className="font-mono text-xs" disabled={busy} value={e.scripts.post} onChange={ev=>patch({scripts:{...e.scripts,post:ev.target.value}})} placeholder={'[{"name":"Success","target":"status","equals":200},{"name":"OK","target":"json","path":"ok","equals":true}]'}/></Field></div>}
        {tab==='Settings'&&<div className="space-y-3"><Field label="Timeout (milliseconds, 1000–120000)"><Input type="number" min={1000} max={120000} disabled={busy} value={e.settings.timeoutMs} onChange={ev=>patch({settings:{timeoutMs:Number(ev.target.value)}})}/></Field><p className="text-sm text-muted">TLS verification enabled. Redirects returned for review. Response limit 2 MB. Form-data supports text fields; use Binary for file uploads.</p></div>}
      </SaSection></div>


      {layout==='horizontal'&&<SaSplitDivider value={editorWidth} onChange={onEditorWidth}/>}
      <div className="min-w-0 resize-y overflow-auto" style={{minHeight:160}}><SaSection title="Response" collapsed={collapsed.response} onToggle={()=>toggle('response')}>{response?<SaResponseViewer key={`${preferences.responseView}-${preferences.jsonDepth}`} preferences={preferences} response={response} checks={checks} previous={previous} history={history.data??[]}/>:<div className="flex min-h-48 flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-line p-5 text-center"><p className="font-display text-lg text-muted">Ready when you are</p><p className="text-sm text-muted">Click Hit / Send to view status, headers and response here.</p></div>}</SaSection></div>
      </div><div className="mt-4">      {selection&&<SaSection title="Version history" collapsed={collapsed.versions} onToggle={()=>toggle('versions')}><p className="font-mono text-xs text-muted">Current version: v{selection.version}</p><p className="text-xs text-muted">Load a version, then Update to restore it as a new version.</p><div className="flex flex-wrap gap-2">{versions.data?.map(v=><Button key={v.id} variant="outline" disabled={busy} onClick={()=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;setE(v.config);setDirty(true)}}>Load v{v.version} · {new Date(v.created_at).toLocaleString()}</Button>)}</div></SaSection>}</div>
      </div>
    </div>
  </div>{chatHost&&createPortal(<div hidden={!active} className="h-full"><SaChatPanel key={chatKey} size={chatSize} onSizeChange={setChatSize} prompt={prompt} onPromptChange={setPrompt} result={ai} busy={busy} onAsk={ask} onApplyRequest={()=>{if(!ai)return;try{patch({...endpointFromRequest(parseCurl(ai.curl)),name:e.name,docs:e.docs,docsHtml:e.docsHtml,collectionId:e.collectionId,variables:e.variables,extracts:e.extracts,settings:e.settings});setResponse(null)}catch(err){setError(err as Error)}}} onApplyDocs={()=>{if(ai){patch({docs:ai.docs,docsHtml:''});setTab('Docs')}}}/></div>,chatHost)}</>
}
