import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, Card, ErrorNote, Field, Input, Select, Textarea } from '../components/ui'
import { CopyButton } from '../components/CopyButton'
import { Markdown } from '../components/Markdown'
import { saPostmanApi } from '../lib/api'
import { endpointFromRequest, parseCurl, type SaEndpoint, type SaField, type SaSaved, type SaResponse, type SaCheck } from '../../shared/saPostman'

const tabs=['Docs','Params','Authorization','Headers','Body','Scripts','Settings','Variables'] as const
function Rows({rows,onChange,disabled}:{rows:SaField[];onChange:(rows:SaField[])=>void;disabled:boolean}){
  return <div className="space-y-2">{rows.map((r,i)=><div key={i} className="flex gap-2">
    <input type="checkbox" aria-label={`Enable row ${i+1}`} disabled={disabled} checked={r.enabled!==false} onChange={ev=>onChange(rows.map((v,j)=>j===i?{...v,enabled:ev.target.checked}:v))}/>
    {(['name','value','description'] as const).map(k=><Input key={k} aria-label={`${k} ${i+1}`} disabled={disabled} placeholder={k} value={r[k]??''} onChange={ev=>onChange(rows.map((v,j)=>j===i?{...v,[k]:ev.target.value}:v))}/>)}
    <Button variant="ghost" disabled={disabled} onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>Delete</Button>
  </div>)}<Button variant="outline" disabled={disabled} onClick={()=>onChange([...rows,{name:'',value:'',description:'',enabled:true}])}>Add row</Button></div>
}
export function SaPostmanPage(){const location=useLocation();return <Workspace key={location.key} incoming={location.state as {curl?:string;title?:string;returnTo?:string}|null}/>}
function Workspace({incoming}:{incoming:{curl?:string;title?:string;returnTo?:string}|null}){
  const qc=useQueryClient()
  const saved=useQuery({queryKey:['sa-endpoints'],queryFn:saPostmanApi.list})
  const history=useQuery({queryKey:['sa-history'],queryFn:saPostmanApi.history})
  const [e,setE]=useState<SaEndpoint>(()=>{try{return {...endpointFromRequest(parseCurl(incoming?.curl??'')),name:incoming?.title??''}}catch{return endpointFromRequest()}})
  const [selection,setSelection]=useState<SaSaved|null>(null)
  const versions=useQuery({queryKey:['sa-versions',selection?.id],queryFn:()=>saPostmanApi.versions(selection!.id),enabled:!!selection})
  const [tab,setTab]=useState<typeof tabs[number]>('Body'),[left,setLeft]=useState('saved'),[curl,setCurl]=useState(incoming?.curl??'')
  const [error,setError]=useState<Error|null>(()=>{if(!incoming?.curl)return null;try{parseCurl(incoming.curl);return null}catch(err){return err as Error}})
  const [busy,setBusy]=useState(false),[response,setResponse]=useState<SaResponse|null>(null),[checks,setChecks]=useState<SaCheck[]>([]),[responseTab,setResponseTab]=useState('body')
  const [prompt,setPrompt]=useState(''),[ai,setAi]=useState<{explanation:string;curl:string;docs:string}|null>(null),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false)
  const patch=(p:Partial<SaEndpoint>)=>{setE(prev=>({...prev,...p}));setDirty(true)}
  const replace=(next:SaEndpoint,sel:SaSaved|null=null)=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;setE(structuredClone(next));setSelection(sel);setDirty(false);setResponse(null);setChecks([]);setError(null);setAi(null)}
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn()}catch(err){setError(err instanceof Error?err:new Error(String(err)))}finally{setBusy(false)}}
  const refresh=()=>{void qc.invalidateQueries({queryKey:['sa-endpoints']});void qc.invalidateQueries({queryKey:['sa-history']});void qc.invalidateQueries({queryKey:['sa-versions']})}
  const hit=()=>action(async()=>{setResponse(null);setChecks([]);const r=await saPostmanApi.execute(e);setResponse(r.response);setChecks(r.checks);if(r.error||r.historyError)setError(new Error(r.error??r.historyError));refresh()})
  const save=(copy=false)=>action(async()=>{const row=selection&&!copy?await saPostmanApi.update(selection.id,selection.version,e):await saPostmanApi.create(e);setSelection(row);setE(row.config);setDirty(false);refresh()})
  const ask=(mode:'generate'|'trace'|'docs'|'ask')=>{const lastError=error?.message??'';return action(async()=>setAi(await saPostmanApi.assist({mode,prompt:prompt.trim()||({generate:'Generate a request based on these endpoint docs.',trace:'Diagnose the response or network error.',docs:'Document this endpoint.',ask:'Review this endpoint and suggest what I should check next.'})[mode],endpoint:e,response:response?JSON.stringify({status:response.status,statusText:response.statusText,headers:Object.fromEntries(Object.entries(response.headers).filter(([key])=>!/cookie|authorization|token|key/i.test(key))),body:response.body}).slice(0,50000):'',error:lastError})))}
  let responseBody=response?.body??'';try{responseBody=JSON.stringify(JSON.parse(responseBody),null,2)}catch{/* text */}
  return <div className="space-y-4 p-5">
    <div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-semibold">SAPostman</h1><p className="text-sm text-muted">Endpoints, documentation and send history.</p>{incoming?.returnTo?.startsWith('/projects/')&&<Link className="text-sm underline" to={incoming.returnTo}>Back to POC</Link>}</div><Button variant="outline" disabled={busy} onClick={()=>replace(endpointFromRequest())}>New request</Button></div>
    <ErrorNote error={error??saved.error??history.error??versions.error}/>
    <div className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)]">
      <Card className="space-y-3 p-3"><div className="flex gap-2"><Button variant="outline" onClick={()=>setLeft('saved')}>Saved</Button><Button variant="outline" onClick={()=>setLeft('history')}>History</Button></div><div className="max-h-[700px] space-y-2 overflow-auto">
        {left==='saved'?(saved.data??[]).map(row=><button disabled={busy} key={row.id} className={`block w-full rounded border p-2 text-left text-sm ${selection?.id===row.id?'border-ember':'border-line'}`} onClick={()=>replace(row.config,row)}><span className="block font-semibold">{row.name}</span><span className="text-xs text-muted">{row.config.method} · v{row.version}</span></button>):(history.data??[]).map(row=><div key={row.id} className="rounded border border-line p-2"><button disabled={busy} className="w-full text-left text-sm" onClick={()=>void action(async()=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;const item=await saPostmanApi.historyItem(row.id);setE(item.request);setSelection(null);setDirty(false);setResponse(item.response);setChecks(item.checks);setError(item.error?new Error(item.error):null)})}><span className="block font-semibold">{row.name}</span><span className="text-xs text-muted">{row.error?'Failed':row.summary.status} · {new Date(row.created_at).toLocaleString()}</span></button><Button variant="ghost" disabled={busy} onClick={()=>void action(async()=>{await saPostmanApi.removeHistory(row.id);refresh()})}>Delete history</Button></div>)}
        {left==='saved'&&!saved.data?.length&&<p className="text-xs text-muted">Save an endpoint to reuse it.</p>}{left==='history'&&<p className="text-xs text-muted">Last 100 sends. Authentication is removed; re-enter credentials before replay.</p>}
      </div></Card>
      <div className="min-w-0 space-y-4"><Card className="space-y-3 p-4">
        <div className="flex flex-wrap items-center gap-2"><Input aria-label="Endpoint name" className="min-w-40 flex-1" disabled={busy} value={e.name} placeholder="Endpoint name" onChange={ev=>patch({name:ev.target.value})}/><Button disabled={busy||!e.name.trim()} onClick={()=>void save()}>{selection?'Update':'Save'}</Button>{selection&&<><Button variant="outline" disabled={busy} onClick={()=>void save(true)}>Save as new</Button><Button variant="ghost" disabled={busy} onClick={()=>{if(confirm('Delete endpoint and all its versions?'))void action(async()=>{await saPostmanApi.remove(selection.id);setSelection(null);setDirty(true);refresh()})}}>Delete endpoint</Button></>}{dirty&&<span className="text-xs text-muted">Unsaved</span>}</div>
        <details><summary className="cursor-pointer text-sm">Import cURL</summary><Textarea aria-label="Import cURL" rows={3} className="mt-2 font-mono text-xs" value={curl} onChange={ev=>setCurl(ev.target.value)}/><Button variant="outline" disabled={busy||!curl.trim()} onClick={()=>{try{replace({...endpointFromRequest(parseCurl(curl)),name:e.name})}catch(err){setError(err as Error)}}}>Import cURL</Button></details>
        <div className="flex flex-wrap gap-2"><Select aria-label="HTTP method" className="w-28" disabled={busy} value={e.method} onChange={ev=>patch({method:ev.target.value})}>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(m=><option key={m}>{m}</option>)}</Select><Input aria-label="Request URL" className="min-w-48 flex-1 font-mono" disabled={busy} value={e.url} onChange={ev=>patch({url:ev.target.value})} placeholder="https://workflows.cekat.ai/webhook/…"/><Button loading={busy} disabled={!e.url.trim()} onClick={()=>void hit()}>Hit / Send</Button></div>
        <div role="tablist" className="flex flex-wrap gap-1 border-b border-line pb-2">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={`rounded px-3 py-2 text-sm ${tab===t?'bg-forest text-paper':'text-muted'}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
        {tab==='Docs'&&<div className="space-y-3"><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?'Edit docs':'Preview docs'}</Button><CopyButton text={e.docs} label="Copy docs"/>{preview?<Markdown>{e.docs||'No documentation yet.'}</Markdown>:<Field label="Endpoint documentation (Markdown)"><Textarea disabled={busy} rows={15} value={e.docs} onChange={ev=>patch({docs:ev.target.value})} placeholder="Purpose, parameters, authentication, request/response examples and error codes."/></Field>}</div>}
        {tab==='Params'&&<><p className="text-xs text-muted">Enabled rows are appended to existing URL query params.</p><Rows rows={e.params} disabled={busy} onChange={params=>patch({params})}/></>}
        {tab==='Headers'&&<Rows rows={e.headers} disabled={busy} onChange={headers=>patch({headers})}/>}
        {tab==='Variables'&&<div className="space-y-3"><p className="text-sm text-muted">Use {'{{base_url}}'}, {'{{token}}'} or {'{{customer_id}}'} in URL, params, headers, auth, body and script rules. Variables are saved per endpoint and version. Values are substituted as literal text.</p><Rows rows={e.variables??[]} disabled={busy} onChange={variables=>patch({variables})}/>{(e.variables??[]).map((v,i)=><label key={i} className="flex items-center gap-2 text-xs"><input type="checkbox" disabled={busy} checked={v.secret??false} onChange={ev=>patch({variables:(e.variables??[]).map((row,j)=>j===i?{...row,secret:ev.target.checked}:row)})}/>Treat {v.name||`variable ${i+1}`} as secret (remove from history and AI)</label>)}</div>}
        {tab==='Authorization'&&<div className="space-y-3"><Field label="Auth type"><Select disabled={busy} value={e.auth.type} onChange={ev=>patch({auth:{...e.auth,type:ev.target.value as SaEndpoint['auth']['type']}})}>{[['none','No Auth'],['basic','Basic Auth'],['bearer','Bearer Token'],['api-key','API Key'],['jwt','JWT Bearer'],['oauth2','OAuth 2.0 access token']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</Select></Field>
          {e.auth.type==='basic'&&(['username','password'] as const).map(k=><Field key={k} label={k}><Input disabled={busy} type={k==='password'?'password':'text'} value={e.auth[k]} onChange={ev=>patch({auth:{...e.auth,[k]:ev.target.value}})}/></Field>)}
          {['bearer','jwt','oauth2'].includes(e.auth.type)&&<Field label="Token"><Input type="password" disabled={busy} value={e.auth.token} onChange={ev=>patch({auth:{...e.auth,token:ev.target.value}})}/></Field>}
          {e.auth.type==='oauth2'&&<p className="text-xs text-muted">Paste an existing access token. Acquire/refresh tokens with your OAuth provider.</p>}
          {e.auth.type==='api-key'&&<>{(['key','value'] as const).map(k=><Field key={k} label={k}><Input disabled={busy} type={k==='value'?'password':'text'} value={e.auth[k]} onChange={ev=>patch({auth:{...e.auth,[k]:ev.target.value}})}/></Field>)}<Select aria-label="API key location" disabled={busy} value={e.auth.location} onChange={ev=>patch({auth:{...e.auth,location:ev.target.value as 'header'|'query'}})}><option value="header">Header</option><option value="query">Query params</option></Select></>}
          <p className="text-xs text-muted">Save stores auth locally and in backups. Send history and AI remove auth fields.</p>
        </div>}
        {tab==='Body'&&<div className="space-y-3"><div className="flex flex-wrap gap-3">{(['none','form-data','urlencoded','raw','binary','graphql'] as const).map(m=><label key={m} className="flex items-center gap-1 text-sm"><input type="radio" name="body-mode" disabled={busy} checked={e.bodyMode===m} onChange={()=>patch({bodyMode:m})}/>{m==='urlencoded'?'x-www-form-urlencoded':m==='graphql'?'GraphQL':m}</label>)}</div>
          {e.bodyMode==='raw'&&<div className="flex gap-2"><Select className="w-40" aria-label="Raw body format" disabled={busy} value={e.rawType} onChange={ev=>patch({rawType:ev.target.value as SaEndpoint['rawType']})}>{['JSON','Text','JavaScript','HTML','XML'].map(t=><option key={t}>{t}</option>)}</Select><Button variant="outline" disabled={busy} onClick={()=>{try{patch({body:JSON.stringify(JSON.parse(e.body),null,2)})}catch{setError(new Error('Beautify requires valid JSON'))}}}>Beautify JSON</Button></div>}
          {['raw','graphql'].includes(e.bodyMode)&&<Field label={e.bodyMode==='graphql'?'GraphQL query':'Request body'}><Textarea aria-label="Request body" disabled={busy} rows={12} className="font-mono text-xs" value={e.body} onChange={ev=>patch({body:ev.target.value})}/></Field>}
          {['form-data','urlencoded'].includes(e.bodyMode)&&<Rows rows={e.form} disabled={busy} onChange={form=>patch({form})}/>}
          {e.bodyMode==='binary'&&<Field label="Binary file (max 2 MB)"><input type="file" disabled={busy} onChange={ev=>{const file=ev.target.files?.[0];if(!file)return;void action(async()=>{if(file.size>2000000)throw new Error('File exceeds 2 MB');const bytes=new Uint8Array(await file.arrayBuffer());let str='';for(const b of bytes)str+=String.fromCharCode(b);patch({binaryName:file.name,binaryBase64:btoa(str)})})}}/><p className="text-xs text-muted">{e.binaryName||'No file selected'}</p></Field>}
          {e.bodyMode==='graphql'&&<Field label="GraphQL variables (JSON)"><Textarea className="font-mono text-xs" disabled={busy} value={e.graphqlVariables} onChange={ev=>patch({graphqlVariables:ev.target.value})}/></Field>}
        </div>}
        {tab==='Scripts'&&<div className="space-y-3"><p className="text-xs text-muted">JSON rules, not JavaScript. Pre-request adds headers/params. Post-response checks status, headers or JSON paths. Invalid rules stop sending.</p><Field label="Pre-request rules"><Textarea rows={5} className="font-mono text-xs" disabled={busy} value={e.scripts.pre} onChange={ev=>patch({scripts:{...e.scripts,pre:ev.target.value}})} placeholder={'{"headers":{"X-Test":"true"},"params":{"debug":"1"}}'}/></Field><Field label="Post-response assertions"><Textarea rows={6} className="font-mono text-xs" disabled={busy} value={e.scripts.post} onChange={ev=>patch({scripts:{...e.scripts,post:ev.target.value}})} placeholder={'[{"name":"Success","target":"status","equals":200},{"name":"OK","target":"json","path":"ok","equals":true}]'}/></Field></div>}
        {tab==='Settings'&&<div className="space-y-3"><Field label="Timeout (milliseconds, 1000–120000)"><Input type="number" min={1000} max={120000} disabled={busy} value={e.settings.timeoutMs} onChange={ev=>patch({settings:{timeoutMs:Number(ev.target.value)}})}/></Field><p className="text-sm text-muted">TLS verification enabled. Redirects returned for review. Response limit 2 MB. Form-data supports text fields; use Binary for file uploads.</p></div>}
      </Card>
      {selection&&<Card className="space-y-2 p-4"><h2 className="font-semibold">Version history · current v{selection.version}</h2><p className="text-xs text-muted">Load a version, then Update to restore it as a new version.</p><div className="flex flex-wrap gap-2">{versions.data?.map(v=><Button key={v.id} variant="outline" disabled={busy} onClick={()=>{if(dirty&&!confirm('Discard unsaved endpoint changes?'))return;setE(v.config);setDirty(true)}}>Load v{v.version} · {new Date(v.created_at).toLocaleString()}</Button>)}</div></Card>}
      <Card className="space-y-3 p-4"><h2 className="font-semibold">Ask your SA</h2><Textarea disabled={busy} rows={2} value={prompt} onChange={ev=>setPrompt(ev.target.value)} placeholder="Describe a request, or ask about an error…"/><p className="text-xs text-muted">Sends endpoint content and response to your configured AI provider. Auth fields are removed. Review payload/response content before submitting.</p><div className="flex flex-wrap gap-2"><Button disabled={busy||!prompt.trim()} onClick={()=>void ask('ask')}>Ask your SA</Button><Button variant="outline" disabled={busy} onClick={()=>void ask('generate')}>Generate request</Button><Button variant="outline" disabled={busy} onClick={()=>void ask('trace')}>Trace error</Button><Button variant="outline" disabled={busy} onClick={()=>void ask('docs')}>Generate docs</Button></div>{ai&&<><Markdown>{ai.explanation}</Markdown>{ai.curl&&<><pre className="overflow-auto whitespace-pre-wrap font-mono text-xs">{ai.curl}</pre><Button variant="outline" disabled={busy} onClick={()=>{try{patch({...endpointFromRequest(parseCurl(ai.curl)),name:e.name,docs:e.docs});setResponse(null)}catch(err){setError(err as Error)}}}>Apply generated request</Button></>}{ai.docs&&<Button variant="outline" disabled={busy} onClick={()=>{patch({docs:ai.docs});setTab('Docs')}}>Apply generated docs</Button>}</>}</Card>
      {response&&<Card className="space-y-3 p-4"><div className="flex flex-wrap gap-3"><h2 className="font-semibold">Response: {response.status} {response.statusText}</h2><span className="text-sm text-muted">{response.durationMs} ms · {response.bytes} bytes</span><CopyButton text={response.body} label="Copy response"/></div>{response.truncated&&<p className="text-warn">Response truncated at 2 MB.</p>}<div className="flex gap-2">{['body','headers','checks'].map(t=><Button key={t} variant="outline" onClick={()=>setResponseTab(t)}>{t}</Button>)}</div>{responseTab==='checks'?<div>{checks.length?checks.map((check,i)=><p key={i} className={check.passed?'text-forest':'text-bad'}>{check.passed?'PASS':'FAIL'} · {check.name} · actual {JSON.stringify(check.actual)}, expected {JSON.stringify(check.expected)}</p>):'No assertions configured.'}</div>:<pre className="max-h-[600px] overflow-auto whitespace-pre-wrap break-all rounded bg-panel p-3 font-mono text-xs">{responseTab==='body'?responseBody||'(empty response)':JSON.stringify(response.headers,null,2)}</pre>}</Card>}
      </div>
    </div>
  </div>
}
