import {useState} from 'react'
import {Button,ErrorNote,Input,Select} from './ui'
interface Rule {name:string;target:'status'|'header'|'json';path?:string;operator?:'equals'|'exists';equals?:unknown}
export function SaAssertions({script,onChange,disabled}:{script:string;onChange:(s:string)=>void;disabled:boolean}){
 const [error,setError]=useState<Error|null>(null)
 let rules:Rule[]=[];let invalid=false
 try{const parsed=script.trim()?JSON.parse(script):[];if(!Array.isArray(parsed))throw Error();rules=parsed}catch{invalid=true}
 const update=(next:Rule[])=>{onChange(JSON.stringify(next,null,2));setError(null)}
 const patch=(i:number,p:Partial<Rule>)=>update(rules.map((r,j)=>i===j?{...r,...p}:r))
 return <div className="space-y-2"><h3 className="font-semibold">Assertion builder</h3>{invalid?<p className="text-xs text-bad">Fix the post-response JSON below before using the builder.</p>:rules.map((r,i)=><div key={i} className="grid gap-2 sm:grid-cols-2"><Input aria-label={`Assertion name ${i+1}`} disabled={disabled} value={r.name} onChange={e=>patch(i,{name:e.target.value})}/><Select aria-label={`Assertion target ${i+1}`} disabled={disabled} value={r.target} onChange={e=>patch(i,{target:e.target.value as Rule['target']})}><option value="status">HTTP status</option><option value="json">JSON field</option><option value="header">Response header</option></Select>{r.target!=='status'&&<Input aria-label={`Assertion path ${i+1}`} disabled={disabled} value={r.path??''} placeholder="data.success / content-type" onChange={e=>patch(i,{path:e.target.value})}/>}<Select disabled={disabled} value={r.operator??'equals'} onChange={e=>patch(i,{operator:e.target.value as Rule['operator']})}><option value="equals">Equals</option><option value="exists">Exists</option></Select>{r.operator!=='exists'&&<Input key={`${i}-${r.target}-${JSON.stringify(r.equals)}`} aria-label={`Assertion expected ${i+1}`} disabled={disabled} defaultValue={JSON.stringify(r.equals)??''} placeholder='200 / true / "value"' onBlur={e=>{try{patch(i,{equals:JSON.parse(e.target.value)})}catch{setError(new Error('Expected value must be JSON: 200, true, null or a quoted string'))}}}/>}<Button variant="ghost" disabled={disabled} onClick={()=>update(rules.filter((_,j)=>j!==i))}>Delete assertion</Button></div>)}<Button variant="outline" disabled={disabled||invalid} onClick={()=>update([...rules,{name:'Success',target:'status',operator:'equals',equals:200}])}>Add assertion</Button><ErrorNote error={error}/></div>
}
