import {useEffect,useRef,useState} from 'react'
import {MessageSquare,PanelRightClose,Maximize2,Minimize2,Eraser,Send,Sparkles,ScanSearch,FileText} from 'lucide-react'
import {Markdown} from './Markdown'
import {Button,Textarea} from './ui'
export type SaChatTurn={role:'user'|'assistant';content:string}
export function SaChatPanel({size,onSizeChange,prompt,onPromptChange,result,busy,onAsk,onApplyRequest,onApplyDocs}:{size:'collapsed'|'normal'|'wide';onSizeChange:(s:'collapsed'|'normal'|'wide')=>void;prompt:string;onPromptChange:(s:string)=>void;result:{explanation:string;curl:string;docs:string}|null;busy:boolean;onAsk:(mode:'ask'|'generate'|'trace'|'docs',history?:SaChatTurn[])=>Promise<void>;onApplyRequest:()=>void;onApplyDocs:()=>void}){
 const [turns,setTurns]=useState<SaChatTurn[]>([]),seen=useRef(result),bottom=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(result&&result!==seen.current){seen.current=result;setTurns(prev=>[...prev,{role:'assistant',content:result.explanation}])}},[result])
 useEffect(()=>{bottom.current?.scrollIntoView?.({block:'nearest'})},[turns,busy,size])
 const send=(mode:'ask'|'generate'|'trace'|'docs'='ask')=>{if(busy)return;const text=prompt.trim()||({ask:'Help me review this API.',generate:'Generate a request.',trace:'Diagnose this response.',docs:'Generate endpoint documentation.'})[mode];const history=turns.slice(-20);setTurns(prev=>[...prev,{role:'user',content:text}]);void onAsk(mode,history);onPromptChange('')}
 if(size==='collapsed')return <aside className="flex rounded-xl border border-line bg-panel lg:sticky lg:top-6 lg:h-[calc(100vh-4rem)] lg:flex-col"><button aria-label="Open Ask your SA" title="Open Ask your SA" className="flex w-full items-center gap-2 px-4 py-3 text-sm font-semibold text-ember lg:flex-col lg:px-0 lg:py-4" onClick={()=>onSizeChange('normal')}><MessageSquare className="size-5"/><span className="lg:[writing-mode:vertical-rl]">Ask your SA</span></button></aside>
 return <aside className="flex h-[calc(100vh-4rem)] min-w-0 flex-col rounded-xl border border-line bg-panel lg:sticky lg:top-6">
  <header className="flex items-center justify-between gap-2 border-b border-line px-4 py-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-ember">Copilot</p><h2 className="font-display text-lg font-semibold leading-none">Ask your SA</h2></div><div className="flex gap-1"><button aria-label="Clear chat" title="Clear chat" className="rounded p-1.5 text-muted" disabled={busy} onClick={()=>{setTurns([]);seen.current=result}}><Eraser className="size-4"/></button><button aria-label="Resize Ask your SA" className="rounded p-1.5 text-muted" onClick={()=>onSizeChange(size==='wide'?'normal':'wide')}>{size==='wide'?<Minimize2 className="size-4"/>:<Maximize2 className="size-4"/>}</button><button aria-label="Collapse Ask your SA" className="rounded p-1.5 text-muted" onClick={()=>onSizeChange('collapsed')}><PanelRightClose className="size-4"/></button></div></header>
  <div className="min-h-0 flex-1 space-y-3 overflow-auto p-4"><p className="text-xs text-muted">Your SA reads the current endpoint, docs, payload and response. Auth fields are removed before sending context.</p>{!turns.length&&<div className="space-y-2">{['Review this API and suggest improvements.','Explain the response and how to troubleshoot it.'].map(text=><button key={text} className="w-full rounded border border-dashed border-line p-2 text-left text-xs" onClick={()=>onPromptChange(text)}>{text}</button>)}</div>}{turns.map((turn,i)=><div key={i} className={`rounded-lg p-3 text-sm ${turn.role==='user'?'bg-forest/10':'border border-line'}`}><p className="mb-1 text-xs font-semibold text-muted">{turn.role==='user'?'You':'Your SA'}</p><Markdown>{turn.content}</Markdown></div>)}{busy&&<p role="status" className="text-xs text-muted">Working…</p>}{result&&turns.length>0&&<div className="flex flex-wrap gap-2">{result.curl&&<Button variant="outline" disabled={busy} onClick={onApplyRequest}>Apply generated request</Button>}{result.docs&&<Button variant="outline" disabled={busy} onClick={onApplyDocs}>Apply generated docs</Button>}</div>}<div ref={bottom}/></div>
  <footer className="space-y-2 border-t border-line p-3"><Textarea aria-label="Ask your SA message" placeholder="Tanya, minta revisi, atau diskusi solusi… (Enter to send)" value={prompt} disabled={busy} rows={3} onChange={ev=>onPromptChange(ev.target.value)} onKeyDown={ev=>{if(ev.key==='Enter'&&!ev.shiftKey&&!ev.nativeEvent.isComposing){ev.preventDefault();if(prompt.trim())send()}}}/><div className="flex flex-wrap gap-1">{(['generate','trace','docs'] as const).map(mode=><Button key={mode} aria-label={mode==='generate'?'Generate request':mode==='trace'?'Trace error':'Generate docs'} title={mode==='generate'?'Generate a request':mode==='trace'?'Analyze the response or error':'Generate endpoint documentation'} icon={mode==='generate'?<Sparkles className="size-3.5"/>:mode==='trace'?<ScanSearch className="size-3.5"/>:<FileText className="size-3.5"/>} variant="ghost" disabled={busy} onClick={()=>send(mode)}>{mode==='generate'?'Generate':mode==='trace'?'Trace':'Docs'}</Button>)}</div><div className="flex justify-end"><Button aria-label="Ask your SA" icon={<Send className="size-4"/>} disabled={busy||!prompt.trim()} onClick={()=>send()}>Send</Button></div></footer>
 </aside>
}
