import {SaApiActions} from './SaLibraryDialog'
import {useState} from 'react'
import {ChevronDown,ChevronRight,ChevronsUp,ChevronsDown,MoreHorizontal,Trash2,Search} from 'lucide-react'
import {Button,Input} from './ui'
import type {SaCollection,SaSaved} from '../../shared/saPostman'

export function SaCollectionTree({collections,requests,selected,busy,onSelect,onMove,onCommand,onCollectionMenu,onTrash}:{collections:SaCollection[];requests:SaSaved[];selected?:string;busy:boolean;onSelect:(row:SaSaved)=>void;onMove:(row:SaSaved,collectionId:string|null)=>Promise<void>;onCommand?:(row:SaSaved,command:string,value?:string)=>Promise<void>;onCollectionMenu?:(c:SaCollection)=>void;onTrash?:(ids:string[])=>Promise<boolean>}){
 const [closed,setClosed]=useState<Record<string,boolean>>({}),[over,setOver]=useState<string|null>(null)
 const [search,setSearch]=useState(''),[menu,setMenu]=useState<SaSaved|null>(null)
 const [checked,setChecked]=useState<Record<string,boolean>>({})
 const visible=requests.filter(r=>!search||`${collections.find(c=>c.id===r.config.collectionId)?.name??'Unfiled'} ${r.name} ${r.config.url}`.toLowerCase().includes(search.toLowerCase()))
 const chosen=visible.filter(r=>checked[r.id]).map(r=>r.id)
 const setCheckedRows=(rows:SaSaved[],value:boolean)=>setChecked(old=>({...old,...Object.fromEntries(rows.map(r=>[r.id,value]))}))
 const groups=[{id:'unfiled',name:'Unfiled'},...collections]
 return <div className="space-y-3" aria-label="API collections"><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted"/><Input className="pl-9!" aria-label="Search collections and APIs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search APIs or collections"/></div>{onTrash&&<div className="grid grid-cols-[minmax(0,1fr)_auto_32px] items-center gap-2 border-b border-line pb-3"><label className="flex cursor-pointer items-center gap-2 text-xs"><input type="checkbox" className="size-3.5 shrink-0 accent-forest" aria-label="Select all APIs" disabled={busy||!visible.length} checked={visible.length>0&&chosen.length===visible.length} ref={node=>{if(node)node.indeterminate=chosen.length>0&&chosen.length<visible.length}} onChange={e=>setCheckedRows(visible,e.target.checked)}/>Select all</label><span className="whitespace-nowrap font-mono text-[10px] text-muted">{chosen.length} selected</span><Button variant="danger" className="h-8 w-8 p-0!" aria-label="Move selected APIs to Trash" title="Move selected APIs to Trash" icon={<Trash2 className="size-4"/>} disabled={busy||!chosen.length} onClick={()=>{const ids=[...chosen];void onTrash(ids).then(success=>{if(success)setChecked(old=>({...old,...Object.fromEntries(ids.map(id=>[id,false]))}))})}}/></div>}<div className="flex items-center justify-between gap-2"><strong className="font-mono text-[10px] font-medium tracking-widest text-muted">COLLECTIONS</strong><div className="flex gap-1"><button className="flex size-7 items-center justify-center rounded text-muted hover:bg-forest-soft" title="Collapse collections" aria-label="Collapse collections" onClick={()=>setClosed(Object.fromEntries(groups.map(g=>[g.id,true])))}><ChevronsUp className="size-4"/><span className="sr-only">Collapse collections</span></button><button className="flex size-7 items-center justify-center rounded text-muted hover:bg-forest-soft" title="Expand collections" aria-label="Expand collections" onClick={()=>setClosed({})}><ChevronsDown className="size-4"/><span className="sr-only">Expand collections</span></button></div></div>{groups.map(group=>{
  const rows=requests.filter(r=>(r.config.collectionId??'unfiled')===group.id&&(!search||`${group.name} ${r.name} ${r.config.url}`.toLowerCase().includes(search.toLowerCase())))
  if(search&&!rows.length&&!group.name.toLowerCase().includes(search.toLowerCase()))return null
  return <div key={group.id} className={`rounded border ${over===group.id?'border-forest bg-forest/10':'border-transparent'}`} onDragOver={ev=>{if(!busy){ev.preventDefault();ev.dataTransfer.dropEffect='move';setOver(group.id)}}} onDragLeave={ev=>{if(!ev.currentTarget.contains(ev.relatedTarget as Node))setOver(null)}} onDrop={ev=>{ev.preventDefault();setOver(null);if(busy)return;const row=requests.find(r=>r.id===ev.dataTransfer.getData('text/sapostman-id'));if(row&&(row.config.collectionId??'unfiled')!==group.id){void onMove(row,group.id==='unfiled'?null:group.id).then(()=>setClosed(prev=>({...prev,[group.id]:false})))}}}>
   <div className="flex min-h-10 items-center gap-1 rounded px-1 hover:bg-forest-soft">{onTrash&&<input type="checkbox" className="mx-1 size-3.5 shrink-0 cursor-pointer accent-forest" aria-label={`Select APIs in ${group.name}`} disabled={busy||!rows.length} checked={rows.length>0&&rows.every(r=>checked[r.id])} ref={node=>{if(node)node.indeterminate=rows.some(r=>checked[r.id])&&!rows.every(r=>checked[r.id])}} onChange={e=>setCheckedRows(rows,e.target.checked)}/>}<button aria-label={`${closed[group.id]?'Expand':'Collapse'} collection ${group.name}`} aria-expanded={!closed[group.id]} onContextMenu={ev=>{ev.preventDefault();const c=collections.find(c=>c.id===group.id);if(c)onCollectionMenu?.(c)}} className="flex min-w-0 flex-1 items-center gap-1.5 rounded py-2 text-left text-xs font-semibold" onClick={()=>setClosed(prev=>({...prev,[group.id]:!prev[group.id]}))}>{closed[group.id]?<ChevronRight className="size-3"/>:<ChevronDown className="size-3"/>}<span className="min-w-0 flex-1 truncate">{group.name}</span><span className="min-w-5 rounded bg-forest-soft px-1 text-center font-mono text-[10px] text-muted">{rows.length}</span></button>{group.id!=='unfiled'&&onCollectionMenu&&<button className="flex size-7 shrink-0 items-center justify-center rounded text-muted hover:bg-forest-soft" aria-label={`Manage collection ${group.name}`} title="Collection options" onClick={()=>{const c=collections.find(c=>c.id===group.id);if(c)onCollectionMenu(c)}}><MoreHorizontal className="size-4"/></button>}</div>
   {(!closed[group.id]||!!search)&&<div className="ml-3 border-l border-line pl-2 space-y-1">{rows.map(row=><div key={row.id} className={`group flex min-h-9 items-center gap-1 rounded-md px-1 ${selected===row.id?'bg-forest text-paper':checked[row.id]?'bg-forest-soft':'hover:bg-forest-soft'}`}>{onTrash&&<input type="checkbox" className="mx-1 size-3.5 shrink-0 cursor-pointer accent-forest" aria-label={`Select API ${row.name}`} disabled={busy} checked={!!checked[row.id]} onChange={e=>setCheckedRows([row],e.target.checked)}/>}<button draggable={!busy} disabled={busy} onContextMenu={ev=>{ev.preventDefault();if(!busy){setMenu(row)}}} onDragStart={ev=>{ev.dataTransfer.setData('text/sapostman-id',row.id);ev.dataTransfer.effectAllowed='move'}} onClick={()=>onSelect(row)} className={`flex min-w-0 flex-1 cursor-grab items-center gap-2 rounded py-2 text-left text-xs active:cursor-grabbing`}><span className={`w-8 shrink-0 font-mono text-[9px] font-medium ${selected===row.id?'text-paper':row.config.method==='GET'?'text-ok':'text-ember'}`}>{row.config.method}</span><span className="min-w-0 truncate" title={row.name}>{row.name}</span></button>{onCommand&&<button aria-label={`API options for ${row.name}`} title="API options" disabled={busy} className={`flex size-7 shrink-0 items-center justify-center rounded ${selected===row.id?'text-paper/70 hover:text-paper':'text-muted hover:bg-forest-soft'}`} onClick={()=>{setMenu(row)}}><MoreHorizontal className="size-3.5"/></button>}</div>)}{!rows.length&&<p className="rounded border border-dashed border-line px-2 py-1.5 text-[11px] text-muted">Drop an API here</p>}</div>}
  </div>
 })}{menu&&onCommand&&<SaApiActions key={menu.id} name={menu.name} collectionId={menu.config.collectionId} collections={collections} busy={busy} onCommand={(command,value)=>void onCommand(menu,command,value)} onClose={()=>setMenu(null)}/>}</div>
}
