import {useState} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Button,Card,ErrorNote,Input,Select} from './ui'
import {SaVariablesEditor} from './SaVariablesEditor'
import {saPostmanApi} from '../lib/api'
import type {SaEnvironment} from '../../shared/saWorkspace'
export function SaEnvironmentPicker({active,onActive}:{active:string;onActive:(id:string)=>void}){
 const qc=useQueryClient(),query=useQuery({queryKey:['sa-environments'],queryFn:saPostmanApi.environments})
 const [draft,setDraft]=useState<SaEnvironment|null>(null),[error,setError]=useState<Error|null>(null),[busy,setBusy]=useState(false)
 const current=query.data?.find(e=>e.id===active)
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn();await qc.invalidateQueries({queryKey:['sa-environments']})}catch(e){setError(e as Error)}finally{setBusy(false)}}
 return <div className="space-y-3"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs uppercase tracking-widest text-muted">Environment</span><div className="w-52 max-w-full"><Select aria-label="Active environment" value={current?.id??''} disabled={busy} onChange={e=>onActive(e.target.value)}><option value="">No environment</option>{query.data?.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</Select></div><Button variant="outline" onClick={()=>setDraft(current?structuredClone(current):{id:'',name:'Dev',variables:[],updated_at:''})}>Manage environments</Button><Button variant="ghost" onClick={()=>setDraft({id:'',name:'',variables:[],updated_at:''})}>Add environment</Button></div><ErrorNote error={error??query.error}/>{draft&&<Card className="space-y-3 p-4"><h2 className="font-display text-lg font-semibold">{draft.id?'Edit environment':'New environment'}</h2><Input aria-label="Environment name" disabled={busy} value={draft.name} placeholder="Dev / Staging / Prod" onChange={e=>setDraft({...draft,name:e.target.value})}/><SaVariablesEditor rows={draft.variables} onChange={variables=>setDraft({...draft,variables})} disabled={busy}/><div className="flex gap-2"><Button disabled={busy||!draft.name.trim()} onClick={()=>void run(async()=>{const saved=draft.id?await saPostmanApi.updateEnvironment(draft):await saPostmanApi.createEnvironment(draft.name,draft.variables);onActive(saved.id);setDraft(null)})}>Save environment</Button>{draft.id&&<Button variant="ghost" disabled={busy} onClick={()=>{if(confirm(`Delete environment ${draft.name}?`))void run(async()=>{await saPostmanApi.deleteEnvironment(draft.id);if(active===draft.id)onActive('');setDraft(null)})}}>Delete environment</Button>}<Button variant="outline" disabled={busy} onClick={()=>setDraft(null)}>Close</Button></div><p className="text-xs text-muted">Saved locally and included in backups. Secret values are masked here; request history and AI context remove them.</p></Card>}</div>
}
