import {useState} from 'react'
import {parse} from 'yaml'
import {importApis,type SaImport} from '../../shared/saImport'
import {saPostmanApi} from '../lib/api'
import {Button,ErrorNote,Input} from './ui'
export function SaImportPanel({onImported,defaultOpen=false}:{onImported:()=>void;defaultOpen?:boolean}){
 const [preview,setPreview]=useState<SaImport|null>(null),[error,setError]=useState<Error|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 return <details open={defaultOpen} className="rounded-lg border border-line bg-panel p-3"><summary className="cursor-pointer text-sm font-medium">Import OpenAPI / Postman / SAPostman</summary><div className="mt-3 space-y-3"><input aria-label="Import API file" type="file" accept=".json,.yaml,.yml" disabled={busy} onChange={ev=>{const file=ev.target.files?.[0];if(!file)return;setPreview(null);setError(null);setMessage('');void (async()=>{try{if(file.size>5000000)throw new Error('Import file exceeds 5 MB');setPreview(importApis(parse(await file.text(),{maxAliasCount:50})))}catch(e){setError(e as Error)}})()}}/><ErrorNote error={error}/>{preview&&<><Input aria-label="Imported collection name" value={preview.name} onChange={e=>setPreview({...preview,name:e.target.value})}/><p className="text-sm">{preview.endpoints.length} APIs · {preview.variables.length} collection variables</p><ul className="max-h-40 overflow-auto text-xs text-muted">{preview.endpoints.map((e,i)=><li key={i}>{e.method} {e.name}</li>)}</ul>{preview.warnings.map((w,i)=><p key={i} className="text-xs text-warn">{w}</p>)}<Button disabled={busy||!preview.name.trim()} onClick={()=>{setBusy(true);setError(null);void saPostmanApi.importCollection(preview).then(r=>{setMessage(`Imported ${r.count} APIs into ${r.collection.name}`);setPreview(null);onImported()}).catch(e=>setError(e as Error)).finally(()=>setBusy(false))}}>Import collection</Button></>}{message&&<p role="status" className="text-sm text-ok">{message}</p>}<p className="text-xs text-muted">Import creates saved APIs; it does not send requests. OpenAPI JSON/YAML uses local references. External refs and Postman JavaScript scripts need manual conversion.</p></div></details>
}
