import {useEffect,useRef,useState} from 'react'
import {Button,ErrorNote,Select} from './ui'
import {saPostmanApi} from '../lib/api'
import {scopedEndpoint,extractVariables,type SaEnvironment,type SaVariable} from '../../shared/saWorkspace'
import type {SaCollection,SaSaved,SaExecution} from '../../shared/saPostman'
export function SaRunner({collections,requests,environment,onFinish,defaultOpen=false}:{collections:SaCollection[];requests:SaSaved[];environment?:SaEnvironment;onFinish:()=>void;defaultOpen?:boolean}){
 const [collection,setCollection]=useState(''),[order,setOrder]=useState<string[]>([]),[running,setRunning]=useState(false),[stopOnFailure,setStopOnFailure]=useState(true),[results,setResults]=useState<{name:string;result?:SaExecution;error?:string}[]>([]),[error,setError]=useState<Error|null>(null),stop=useRef(false),execution=useRef<string|null>(null)
 useEffect(()=>()=>{stop.current=true;if(execution.current)void saPostmanApi.cancelExecution(execution.current).catch(()=>{})},[])
 const choose=(id:string)=>{setCollection(id);setOrder(requests.filter(r=>r.config.collectionId===id).map(r=>r.id));setResults([])}
 const run=async()=>{setRunning(true);setResults([]);setError(null);stop.current=false;let session:SaVariable[]=[];try{for(const id of order){if(stop.current)break;const row=requests.find(r=>r.id===id);if(!row)throw new Error('A selected API was deleted. Select the collection again.');const c=collections.find(c=>c.id===collection);let failed=false;try{const e=scopedEndpoint(row.config,c?.variables,environment?.variables,session);execution.current=crypto.randomUUID();const result=await saPostmanApi.execute(e,execution.current);execution.current=null;failed=!!result.error||!result.response||result.response.status>=400||result.checks.some(c=>!c.passed);if(!failed&&result.response){const extracted=extractVariables(row.config,result.response);session=[...session.filter(v=>!extracted.some(n=>n.name===v.name)),...extracted]}setResults(prev=>[...prev,{name:row.name,result}])}catch(e){execution.current=null;failed=true;setResults(prev=>[...prev,{name:row.name,error:e instanceof Error?e.message:String(e)}])}if(failed&&stopOnFailure)break}}catch(e){setError(e as Error)}finally{execution.current=null;setRunning(false);onFinish()}}
 return <details open={defaultOpen} className="rounded-lg border border-line bg-panel p-3"><summary className="cursor-pointer text-sm font-medium">Collection Runner</summary><div className="mt-3 space-y-3"><div className="flex flex-wrap items-center gap-2"><Select className="w-60" aria-label="Runner collection" disabled={running} value={collection} onChange={e=>choose(e.target.value)}><option value="">Select collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><span className="text-xs text-muted">Environment: {environment?.name??'none'}</span><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={stopOnFailure} disabled={running} onChange={e=>setStopOnFailure(e.target.checked)}/>Stop on failure</label></div>{order.map((id,i)=><div key={id} className="flex items-center gap-2 text-sm"><span className="flex-1">{i+1}. {requests.find(r=>r.id===id)?.name??'Deleted API'}</span><Button variant="ghost" disabled={running||i===0} aria-label={`Move runner request ${i+1} up`} onClick={()=>setOrder(prev=>{const next=[...prev];[next[i-1],next[i]]=[next[i],next[i-1]];return next})}>↑</Button><Button variant="ghost" disabled={running||i===order.length-1} aria-label={`Move runner request ${i+1} down`} onClick={()=>setOrder(prev=>{const next=[...prev];[next[i+1],next[i]]=[next[i],next[i+1]];return next})}>↓</Button><Button variant="ghost" disabled={running} onClick={()=>setOrder(prev=>prev.filter(v=>v!==id))}>Exclude</Button></div>)}<div className="flex gap-2"><Button disabled={running||!order.length} onClick={()=>void run()}>Run collection</Button>{running&&<><Button variant="danger" onClick={()=>{stop.current=true;if(execution.current)void saPostmanApi.cancelExecution(execution.current).catch(e=>setError(e as Error))}}>Cancel now</Button><Button variant="outline" onClick={()=>{stop.current=true}}>Stop after current request</Button></>}</div><ErrorNote error={error}/>{results.map((r,i)=><p key={i} className={`text-sm ${r.error||r.result?.error||r.result?.checks.some(c=>!c.passed)||(r.result?.response?.status??0)>=400?'text-bad':'text-ok'}`}>{r.name} · {r.error??r.result?.error??`${r.result?.response?.status} · ${r.result?.response?.durationMs} ms · ${r.result?.checks.filter(c=>c.passed).length}/${r.result?.checks.length} checks`}</p>)}<p className="text-xs text-muted">Runs only after Run collection. Configure JSON response extractions in Scripts to pass tokens or IDs to following APIs. Extracted variables exist only during this run; each request is recorded in send history.</p></div></details>
}
