import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { workspaceApi, type SkillRelease } from '../lib/api'
import type { Skill } from '../lib/types'
import { Button, ErrorNote } from './ui'
export function SkillUpdates() {
 const qc=useQueryClient()
 const releases=useQuery({queryKey:['skill-releases'],queryFn:workspaceApi.releases})
 const [preview,setPreview]=useState<{release:SkillRelease;skill?:Skill}>()
 const apply=useMutation({mutationFn:(mode:'copy'|'replace')=>workspaceApi.applyRelease(preview!.release.release,mode,preview!.skill),onSuccess:async()=>{setPreview(undefined);await Promise.all([qc.invalidateQueries({queryKey:['skills']}),qc.invalidateQueries({queryKey:['skill-releases']}),qc.invalidateQueries({queryKey:['skill-history']})])}})
 const available=(releases.data??[]).filter(r=>!r.installed.length||r.installed.some(s=>s.available))
 return <details className="rounded-xl border border-line bg-panel p-4"><summary className="cursor-pointer font-semibold">Built-in skill updates{releases.data?` (${available.length})`:''}</summary><p className="mt-3 text-sm text-muted">Preview a release before applying. Save as a new skill to keep your current instructions and default selection. Replacing a skill saves its previous instructions in version history.</p><ErrorNote error={releases.error??apply.error}/><div className="mt-3 space-y-2">{available.map(r=><div key={r.release} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-line p-3"><div><p className="text-sm font-medium">{r.builtin.name}</p><p className="text-xs text-muted">Release {r.release} · {r.installed.some(s=>s.customized)?'Local customization detected':r.installed.length?'Built-in update available':'Not installed'}</p></div><Button variant="outline" onClick={()=>{apply.reset();setPreview({release:r,skill:r.installed.find(s=>s.available)})}}>Preview update</Button></div>)}{releases.data&&!available.length&&<p className="text-sm text-muted">Built-in skills are up to date.</p>}</div>{preview&&<div className="mt-4 space-y-3 border-t border-line pt-4"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{preview.release.builtin.name}</h3><Button variant="outline" disabled={apply.isPending} onClick={()=>setPreview(undefined)}>Close preview</Button></div><div className="grid gap-3 lg:grid-cols-2"><div><p className="mb-2 text-xs font-semibold">Current instructions</p><p className="mb-2 text-xs text-muted">{preview.skill?.description}</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-paper p-3 text-xs">{preview.skill?.instructions??'No installed version'}</pre></div><div><p className="mb-2 text-xs font-semibold">New built-in instructions</p><p className="mb-2 text-xs text-muted">{preview.release.builtin.description}</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-paper p-3 text-xs">{preview.release.builtin.instructions}</pre></div></div><div className="flex flex-wrap gap-2"><Button loading={apply.isPending} onClick={()=>apply.mutate('copy')}>Save as new skill</Button>{preview.skill&&<Button variant="outline" disabled={apply.isPending} onClick={()=>apply.mutate('replace')}>Replace current skill · keep previous version</Button>}</div></div>}</details>
}
export function SkillHistory({skillId,onRestore}:{skillId:string;onRestore:(skill:Skill)=>void}) {
 const history=useQuery({queryKey:['skill-history',skillId],queryFn:()=>workspaceApi.skillHistory(skillId)})
 return <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-medium">Version history ({history.data?.length??0})</summary><ErrorNote error={history.error}/><div className="mt-3 space-y-3">{history.data?.map(version=><div key={version.id} className="rounded border border-line p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted">{new Date(version.created_at).toLocaleString('en-US')}</p><Button variant="outline" onClick={()=>onRestore(version.snapshot)}>Load into editor</Button></div><details className="mt-2"><summary className="cursor-pointer text-xs">View instructions</summary><pre className="mt-2 max-h-60 overflow-auto whitespace-pre-wrap text-xs">{version.snapshot.instructions}</pre></details></div>)}</div></details>
}
