// POC n8n workflow: ONE complete, importable gateway workflow for the whole POC (one webhook, each use case routed
// by its "action"), with one complete cURL per use case. Generated by AI (scope 'n8n') and editable in the POC.
import { WEBHOOK_URL_PLACEHOLDER, curlCommand } from './pocCurl.ts'

/** One use case of the gateway: the "action" Switch Action routes on, and the one cURL that exercises it. */
export type PocN8nCase = { action: string; title: string; curl: string }

export type PocN8nWorkflow = {
  name: string
  description: string
  /** n8n workflow export JSON, as text so the SA can edit it; may be invalid while editing. */
  json: string
  /** 1 use case = 1 cURL, all against this workflow's webhook. */
  cases: PocN8nCase[]
  testNotes: string
}

export type PocN8n = { workflows: PocN8nWorkflow[] }

export const emptyN8n = (): PocN8n => ({ workflows: [] })

/**
 * The "skill" the AI follows when it writes the POC n8n workflow and its cURL examples. The structure follows an
 * exported n8n workflow (e.g. "Siloam Procurement Gateway - POC 01.json"): node names, types, parameter shapes,
 * connections and workflow metadata.
 */
export const N8N_WORKFLOW_RULES = [
  '# N8N WORKFLOW RULES (POC)',
  'Write ONE complete, importable n8n workflow for the whole POC — a gateway. Every API integration of the POC is one use case, identified by an "action" value equal to the integration name, and every use case is represented and routed distinctly inside this one workflow. 1 use case = 1 cURL. Comprehensive and production-like, never a stub.',
  'Workflow export shape: { "name": "<Client> <Purpose> Gateway - POC 01", "nodes": [ … ], "connections": { … }, "settings": { "executionOrder": "v1", "binaryMode": "separate" } }.',
  'Node shape: { "name": "<descriptive name>", "type": "n8n-nodes-base.<node>", "typeVersion": <number>, "parameters": { … } }, plus "credentials": { "<credential type>": { "name": "<credential name>" } } where the node needs one — names only, never ids or secrets.',
  'Nodes, in this order:',
  '1. "Webhook Trigger" (n8n-nodes-base.webhook, typeVersion 1.1): parameters { "httpMethod": "POST", "path": "<path of the API integrations\' webhookAddress on https://workflows.cekat.ai/webhook/>", "responseMode": "responseNode", "options": {} }. All API integrations of the POC call this one webhook.',
  '2. "Validate & Extract Payload" (n8n-nodes-base.code, typeVersion 2, parameters.jsCode, JavaScript): read const body = $input.item.json.body || $input.item.json || {}; check "action" is one of the allowed actions; validate the common fields and, per action, its required fields, types and formats (phone 62…, email, dates YYYY-MM-DD); return { valid, errors, action, payload }.',
  '3. "Is Payload Valid?" (n8n-nodes-base.if, typeVersion 1): true → "Switch Action"; false → "Format Validation Error" (Code node) → "Respond to Webhook" with a clear message listing what is wrong.',
  '4. "Switch Action" (n8n-nodes-base.switch, typeVersion 1): parameters { "dataType": "string", "value1": "={{ $json.action }}", "rules": { "rules": [ { "value2": "<action>", "output": <index> }, … ] } } — one output per use case, in the order of the use cases.',
  '5. One branch per use case: generate identifiers in a Code node whenever it creates something (e.g. "Gen Ticket ID & Calculate SLA": a ticket id like TKT-YYYYMMDD-XXXX from the date plus a random or sequential suffix); authenticate to the client system first when it has an authUrl, then call the client API with an HTTP Request node (n8n-nodes-base.httpRequest, typeVersion 4.1; targetUrl, targetMethod, mapped fields); read or write the Cekat CRM with n8n-nodes-base.cekatCrm (see the CEKAT N8N NODES catalog): search { "operation": "searchItems", "boardId", "searchConditions": { "condition": [ { "column_name", "value" } ] } } and create { "resource": "action", "boardId", "groupId", "itemName", "columns": { "column": [ { "columnName", "stringValue" } | { "columnName", "valueType": "select", "selectValue": "=<number>" } ] } }; branch with IF/Switch on found / not found and on client errors (4xx/5xx).',
  '6. Select/Dropdown values for the Cekat CRM are zero-based option numbers: the first option is 0, never 1 (e.g. "selectValue": "=0" for the first option); map labels to numbers in a Code node.',
  '7. Every branch ends in a "Format <result> Response" Code node that flows into ONE shared "Respond to Webhook" (n8n-nodes-base.respondToWebhook) returning a compact JSON the Cekat AI can relay (e.g. { "success": true, "action": "…", "ticket_id": "…", "message": "…" }).',
  'Connections: { "<source node name>": { "main": [ [ { "node": "<target node name>", "type": "main", "index": 0 } ], … ] } } — one inner array per output, in output order (IF: true first, then false; Switch: one per rule). Node names must match exactly.',
  'Write no node ids, positions or webhookId — SA Copilot adds them. Keep Code nodes short and focused.',
  'For every use case write one complete cURL: POST to the full webhook URL, every header (Content-Type: application/json, and Authorization: Bearer <API key> when the integration has one) and a JSON body with "action": "<action>" first and EVERY field of that integration\'s AI Input schema filled with realistic dummy data in the project language. It must run as-is in a terminal or Postman (single-quoted, POSIX shell).',
  'Test notes: what each cURL should return and one failing variation to try.',
].join('\n')

const text = (v: unknown) => (typeof v === 'string' ? v.trim() : '')
const records = (v: unknown): Record<string, unknown>[] => (Array.isArray(v) ? v.filter((x) => x && typeof x === 'object') : [])

const stripFences = (raw: string) =>
  raw
    .trim()
    .replace(/^```(?:json)?\s*\n?/i, '')
    .replace(/\n?```$/, '')
    .trim()

export type ParsedWorkflow = { ok: true; workflow: Record<string, unknown> } | { ok: false; error: string }

export type WorkflowSecret = { path: (string | number)[]; value: unknown; placeholder: string }

const SENSITIVE_KEY = /(api[_-]?key|access[_-]?token|refresh[_-]?token|authorization|password|client[_-]?secret|private[_-]?key|credential|webhookId|instanceId|secret|token)/i

function redactValue(value: unknown, path: (string | number)[], secrets: WorkflowSecret[]): unknown {
  if (Array.isArray(value)) return value.map((item, index) => redactValue(item, [...path, index], secrets))
  if (!value || typeof value !== 'object') return value

  return Object.fromEntries(Object.entries(value).map(([key, child]) => {
    const childPath = [...path, key]
    if (SENSITIVE_KEY.test(key) && child !== null && child !== '') {
      const index = secrets.length
      const placeholder = `[REDACTED_SECRET_${index}]`
      secrets.push({ path: childPath, value: structuredClone(child), placeholder })
      return [key, placeholder]
    }
    return [key, redactValue(child, childPath, secrets)]
  }))
}

/** Remove credential-like values from a workflow before sending it to an external model. */
export function redactWorkflowSecrets<T>(workflow: T): { workflow: T; secrets: WorkflowSecret[] } {
  const secrets: WorkflowSecret[] = []
  return { workflow: redactValue(workflow, [], secrets) as T, secrets }
}

/** Restore secrets only when the AI proposal keeps every original secret-bearing field in place. */
export function restoreWorkflowSecrets<T>(workflow: T, secrets: WorkflowSecret[]): T {
  const result = structuredClone(workflow)
  for (const secret of secrets) {
    let parent: unknown = result
    for (const segment of secret.path.slice(0, -1)) {
      if (!parent || typeof parent !== 'object' || !(segment in parent)) {
        throw new Error('The AI proposal removed a secret-bearing field; review it manually instead.')
      }
      parent = (parent as Record<string | number, unknown>)[segment]
    }
    const last = secret.path.at(-1)
    if (last === undefined || !parent || typeof parent !== 'object' || !(last in parent)) {
      throw new Error('The AI proposal removed a secret-bearing field; review it manually instead.')
    }
    if ((parent as Record<string | number, unknown>)[last] !== secret.placeholder) {
      throw new Error('The AI proposal changed a redacted secret-bearing field; review it manually instead.')
    }
    ;(parent as Record<string | number, unknown>)[last] = structuredClone(secret.value)
  }
  return result
}

export type PreparedWorkflowReview<T extends Record<string, unknown> = Record<string, unknown>> = {
  workflow: T
  secrets: WorkflowSecret[]
  preserved: Record<string, unknown>
}

const PRESERVED_WORKFLOW_FIELDS = ['active', 'id', 'meta', 'pinData', 'tags', 'versionId']

/** Remove execution samples and instance metadata, and redact credential values before external review. */
export function prepareWorkflowReview<T extends Record<string, unknown>>(workflow: T): PreparedWorkflowReview<T> {
  const reviewable = structuredClone(workflow)
  const preserved: Record<string, unknown> = {}
  for (const key of PRESERVED_WORKFLOW_FIELDS) {
    if (key in reviewable) {
      preserved[key] = reviewable[key]
      delete reviewable[key]
    }
  }
  const redacted = redactWorkflowSecrets(reviewable)
  return { workflow: redacted.workflow, secrets: redacted.secrets, preserved }
}

/** Reattach local metadata and credentials to a reviewed workflow proposal after validation. */
export function restoreWorkflowReview<T extends Record<string, unknown>>(
  workflow: Record<string, unknown>,
  prepared: PreparedWorkflowReview<T>,
): Record<string, unknown> {
  return { ...restoreWorkflowSecrets(workflow, prepared.secrets), ...structuredClone(prepared.preserved) }
}

/** Whether text is an importable n8n workflow export. */
export function parseWorkflow(json: string): ParsedWorkflow {
  let value: unknown
  try {
    value = JSON.parse(json)
  } catch (e) {
    return { ok: false, error: `Invalid JSON: ${e instanceof Error ? e.message : String(e)}` }
  }
  const w = value as { nodes?: unknown; connections?: unknown }
  if (!value || typeof value !== 'object' || Array.isArray(value) || !Array.isArray(w.nodes) || !w.connections || typeof w.connections !== 'object') {
    return { ok: false, error: 'An n8n workflow needs a "nodes" array and a "connections" object' }
  }
  return { ok: true, workflow: value as Record<string, unknown> }
}

const COLUMN_GAP = 240
const ROW_GAP = 160
const CENTER_Y = 300

/** Target node names per source node, from n8n's `connections` ({source: {main: [[{node}], …]}}). */
function outgoing(connections: unknown): Map<string, string[]> {
  const out = new Map<string, string[]>()
  for (const [source, byType] of Object.entries(connections && typeof connections === 'object' ? connections : {})) {
    const targets = Object.values(byType && typeof byType === 'object' ? byType : {})
      .flat(2)
      .map((link) => (link && typeof link === 'object' ? text((link as { node?: unknown }).node) : ''))
      .filter(Boolean)
    out.set(source, targets)
  }
  return out
}

/** Step (column) of each node: the longest path from a start node, ignoring edges that loop back. */
function columns(names: string[], out: Map<string, string[]>): Map<string, number> {
  const incoming = new Set([...out.values()].flat())
  const roots = names.filter((n) => !incoming.has(n))
  const state = new Map<string, 'open' | 'done'>()
  const order: string[] = []
  const forward = new Map<string, string[]>()
  const visit = (n: string) => {
    state.set(n, 'open')
    const next = (out.get(n) ?? []).filter((v) => names.includes(v) && state.get(v) !== 'open')
    forward.set(n, next)
    for (const v of next) if (!state.has(v)) visit(v)
    state.set(n, 'done')
    order.push(n)
  }
  for (const n of [...roots, ...names]) if (!state.has(n)) visit(n)
  const column = new Map(names.map((n) => [n, 0]))
  for (const n of order.reverse()) for (const v of forward.get(n) ?? []) column.set(v, Math.max(column.get(v) ?? 0, (column.get(n) ?? 0) + 1))
  return column
}

/**
 * Adds the node ids and canvas positions the model leaves out (to save output tokens): left to right by step,
 * nodes of the same step stacked vertically. Ids and positions already present are kept.
 */
export function completeWorkflowLayout(workflow: Record<string, unknown>): Record<string, unknown> {
  const nodes = records(workflow.nodes)
  const names = nodes.map((n) => text(n.name))
  const column = columns(names, outgoing(workflow.connections))
  const perColumn = new Map<number, string[]>()
  for (const name of names) perColumn.set(column.get(name) ?? 0, [...(perColumn.get(column.get(name) ?? 0) ?? []), name])
  const position = (name: string) => {
    const col = column.get(name) ?? 0
    const stack = perColumn.get(col) ?? [name]
    return [col * COLUMN_GAP, Math.round(CENTER_Y + (stack.indexOf(name) - (stack.length - 1) / 2) * ROW_GAP)]
  }
  return {
    ...workflow,
    nodes: nodes.map((n) => ({
      ...n,
      id: text(n.id) || globalThis.crypto.randomUUID(),
      position: Array.isArray(n.position) && n.position.length === 2 ? n.position : position(text(n.name)),
    })),
  }
}

const WEBHOOK_TYPE = 'n8n-nodes-base.webhook'

/** Fills the workflow metadata and webhook ids an n8n export carries; values already present are kept. */
export function completeWorkflowExport(workflow: Record<string, unknown>): Record<string, unknown> {
  const settings = workflow.settings && typeof workflow.settings === 'object' ? workflow.settings : {}
  return {
    ...workflow,
    nodes: records(workflow.nodes).map((n) => (n.type === WEBHOOK_TYPE && !text(n.webhookId) ? { ...n, webhookId: globalThis.crypto.randomUUID() } : n)),
    pinData: workflow.pinData ?? {},
    settings: { executionOrder: 'v1', binaryMode: 'separate', ...settings },
    active: workflow.active ?? false,
    tags: workflow.tags ?? [],
  }
}

function workflowText(raw: unknown): string {
  const json = stripFences(text(raw))
  const parsed = parseWorkflow(json)
  return parsed.ok ? JSON.stringify(completeWorkflowExport(completeWorkflowLayout(parsed.workflow)), null, 2) : json
}

const FENCED = /```[^\n]*\n([\s\S]*?)(?:```|$)/

/** The content of the first fenced block (any label, prose around it dropped), else the text itself. */
const cleanCurl = (raw: string) => (FENCED.exec(raw)?.[1] ?? raw).trim()

/** Stored limits (server/validation.ts), so an AI answer always saves. */
const LIMITS = { name: 200, description: 5_000, testNotes: 5_000, action: 120, title: 500, curl: 20_000, cases: 50 }
const DEFAULT_NAME = 'n8n gateway workflow'

/** Use cases without a cURL are dropped: 1 use case = 1 cURL. */
function casesFromAi(raw: unknown): PocN8nCase[] {
  return records(raw)
    .map((c) => ({ action: text(c.action).slice(0, LIMITS.action), title: text(c.title).slice(0, LIMITS.title), curl: cleanCurl(text(c.curl)).slice(0, LIMITS.curl) }))
    .filter((c) => c.curl)
    .slice(0, LIMITS.cases)
}

/** The model's use cases, or — when it wrote none — one per action the workflow's Switch routes on. */
function workflowCasesFromAi(raw: unknown, json: string): PocN8nCase[] {
  const cases = casesFromAi(raw)
  if (cases.length) return cases
  const parsed = parseWorkflow(json)
  return parsed.ok ? casesFromWorkflow(parsed.workflow).slice(0, LIMITS.cases) : []
}

/** The model's workflow in the stored shape; empty ones are dropped, invalid JSON is kept for editing. */
export function n8nFromAi(raw: unknown): PocN8n {
  const workflows = records(raw && typeof raw === 'object' ? (raw as { workflows?: unknown }).workflows : undefined)
    .map((w) => {
      const json = workflowText(w.workflowJson)
      return {
        name: (text(w.name) || DEFAULT_NAME).slice(0, LIMITS.name),
        description: text(w.description).slice(0, LIMITS.description),
        json,
        cases: workflowCasesFromAi(w.cases, json),
        testNotes: text(w.testNotes).slice(0, LIMITS.testNotes),
      }
    })
    .filter((w) => w.json && w.json !== '{}')
  return { workflows }
}

const CEKAT_WEBHOOK_BASE = 'https://workflows.cekat.ai/webhook/'
const ACTION_FIELD = /\$json\.action\b|\$json\[['"]action['"]\]/

/** Actions a Switch node routes on: v1 (value1 = action, rules.rules[].value2) or v3 (conditions on $json.action). */
function switchActions(parameters: Record<string, unknown>): string[] {
  const rules = (parameters.rules ?? {}) as Record<string, unknown>
  if (ACTION_FIELD.test(text(parameters.value1))) return records(rules.rules).map((r) => text(r.value2))
  return records(rules.values).flatMap((v) =>
    records((v.conditions as { conditions?: unknown } | undefined)?.conditions)
      .filter((c) => ACTION_FIELD.test(text(c.leftValue)))
      .map((c) => text(c.rightValue)),
  )
}

/** The use cases of an exported gateway workflow: one per action its Switch routes on, each with a cURL to its webhook. */
export function casesFromWorkflow(workflow: Record<string, unknown>): PocN8nCase[] {
  const nodes = records(workflow.nodes)
  const webhook = nodes.find((n) => n.type === WEBHOOK_TYPE)?.parameters as Record<string, unknown> | undefined
  const path = text(webhook?.path).replace(/^\/+/, '')
  const url = path ? `${CEKAT_WEBHOOK_BASE}${path}` : WEBHOOK_URL_PLACEHOLDER
  const method = text(webhook?.httpMethod) || 'POST'
  const actions = nodes
    .filter((n) => n.type === 'n8n-nodes-base.switch')
    .flatMap((n) => switchActions((n.parameters ?? {}) as Record<string, unknown>))
    .filter(Boolean)
  return [...new Set(actions)].map((action) => ({ action, title: '', curl: curlCommand({ method, url, body: { action } }) }))
}

/**
 * How the model writes one workflow as plain text. Text streams through proxies such as 9router as it is
 * written (tool-call arguments are buffered until the end), and the workflow JSON needs no escaping.
 */
export const WORKFLOW_TEXT_FORMAT = [
  'Answer with exactly these sections, in this order, and nothing else:',
  '## NAME',
  '<workflow name>',
  '## DESCRIPTION',
  '<what it does: the shared steps, then each use case branch, one short paragraph>',
  '## WORKFLOW',
  '```json',
  '<the complete n8n workflow export: {"name","nodes":[…],"connections":{…},"settings":{"executionOrder":"v1","binaryMode":"separate"}}>',
  '```',
  '## CASES',
  '### <action of the first use case>',
  '<one-line title of the use case>',
  '```bash',
  '<the complete cURL request for this use case>',
  '```',
  '### <action of the next use case — one ### block per use case, 1 use case = 1 cURL>',
  '…',
  '## TEST NOTES',
  '<expected response of each cURL and one failing variation to try>',
].join('\n')

const SECTION_RE = /^##\s+(NAME|DESCRIPTION|WORKFLOW|CASES|TEST NOTES)\s*$/gm
const CASE_RE = /^###\s+(.+?)\s*$/gm

/** Text between each heading match and the next one. */
function splitByHeadings(source: string, re: RegExp): [string, string][] {
  const marks = [...source.matchAll(re)]
  return marks.map((m, i) => {
    const start = (m.index ?? 0) + m[0].length
    const end = i + 1 < marks.length ? (marks[i + 1].index ?? source.length) : source.length
    return [m[1], source.slice(start, end).trim()]
  })
}

/** The use cases of the CASES section: action heading, title line(s), then the fenced cURL. */
function parseCases(section: string): PocN8nCase[] {
  const blocks = splitByHeadings(section, CASE_RE)
  // A model that skips the ### headings still wrote a cURL: keep it as one use case.
  const cases = blocks.length ? blocks : section.trim() ? [['', section.trim()] as [string, string]] : []
  return cases.map(([action, body]) => {
    const fence = body.indexOf('```')
    return { action, title: fence === -1 ? '' : body.slice(0, fence).trim(), curl: cleanCurl(body) }
  })
}

export type WorkflowSections = { name: string; description: string; workflowJson: string; cases: PocN8nCase[]; testNotes: string }

/** One workflow written in WORKFLOW_TEXT_FORMAT, in the shape n8nFromAi reads; null without a WORKFLOW section. */
export function parseWorkflowSections(text: string): WorkflowSections | null {
  const sections = Object.fromEntries(splitByHeadings(text, SECTION_RE))
  if (!sections.WORKFLOW) return null
  return {
    name: sections.NAME ?? '',
    description: sections.DESCRIPTION ?? '',
    workflowJson: stripFences(sections.WORKFLOW),
    cases: parseCases(sections.CASES ?? ''),
    testNotes: sections['TEST NOTES'] ?? '',
  }
}

/** A workflow as stored before use cases existed: one cURL and the API integration it served. */
export type LegacyWorkflow = Partial<PocN8nWorkflow> & { tool?: string; curl?: string }

/** The use cases of a stored workflow; a legacy single cURL becomes one use case. */
export const workflowCases = (w: LegacyWorkflow): PocN8nCase[] =>
  w.cases ?? (w.curl?.trim() ? [{ action: w.tool ?? '', title: w.name ?? '', curl: w.curl }] : [])

/** POCs saved before n8n workflows existed get an empty list; a legacy single cURL becomes one use case. */
export function normalizeN8n(n8n: { workflows?: LegacyWorkflow[] } | undefined): PocN8n {
  return {
    workflows: (n8n?.workflows ?? []).map((w) => ({
      name: w.name ?? '',
      description: w.description ?? '',
      json: w.json ?? '',
      cases: workflowCases(w),
      testNotes: w.testNotes ?? '',
    })),
  }
}
